### ISSUE TITLE
eventlet.green.ssl incompatible with Python >=2.7.9

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#135]
`_ssl.sslwrap()` does not exist in Python >=2.7.9 (since http://hg.python.org/cpython/rev/221a1f9155e2).
This causes additional error in test suite of Eventlet:

```
======================================================================
ERROR: test_ssl_connect (tests.ssl_test.SSLTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/eventlet-0.15.2/tests/ssl_test.py", line 83, in test_ssl_connect
    ssl_client.connect(('127.0.0.1', sock.getsockname()[1]))
  File "/tmp/eventlet-0.15.2/eventlet/green/ssl.py", line 249, in connect
    self._sslobj = _ssl.sslwrap(self._sock, False, self.keyfile, self.certfile,
AttributeError: 'module' object has no attribute 'sslwrap'
```

Originally reported here: https://bitbucket.org/eventlet/eventlet/issue/165/eventletgreenssl-incompatible-with-python

Eventlet SSL integration should have more attention in next releases.

**Comment by temoto** [comment]
@dofelw @conslo v0.16 was released just before new year holidays.
https://pypi.python.org/pypi/eventlet/0.16.0
