### ISSUE TITLE
Incompatibility with multiprocessing.pool in Python 2.7.x

### ISSUE THREAD

**Issue by julkiewicz** [eventlet/eventlet#147]
I get the following error when using eventlet together with gunicorn. This happens upon attempt to gracefully terminate a worker process:

```
File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
  self.run()
File "/usr/lib/python2.7/threading.py", line 761, in run
  self.__target(*self.__args, **self.__kwargs)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 324, in _handle_workers
  while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
AttributeError: '_MainThread' object has no attribute '_state'
```

Indeed, `multiprocessing.pool` seems to be based on a non-public property `_state` which seems to have three possible states `RUN` `CLOSE` and `TERMINATE`. Not sure what is the difference between `CLOSE` and `TERMINATE`. The appropriate fix would probably be to implement `_state` as an assignable property somehow.

**Comment by smtakeda** [comment]
I came across the same error in Python 3.4.3 on Centos 6.5

Here is a test case:
```
from multiprocessing.pool import ThreadPool
import time
import eventlet
eventlet.monkey_patch()

def run_this(idx):
    print('hello {0}-1'.format(idx))
    time.sleep(1)
    print('hello {0}-2'.format(idx))

pool = ThreadPool(10)

for idx in range(10):
    pool.apply_async(run_this, [idx])

pool.close()
pool.join()
```

```
(eventlet_requests)stakeda@stakeda /tmp>python test.py 
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 365, in _handle_workers
    while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
AttributeError: '_MainThread' object has no attribute '_state'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 379, in _handle_tasks
    if thread._state:
AttributeError: '_MainThread' object has no attribute '_state'
```

```
(eventlet_requests) $>pip list
eventlet (0.18.1)
greenlet (0.4.9)
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)
```

**Comment by booxter** [comment]
When we monkey patch, we get _MainThread from current_thread call. But when we don't monkey patch, we get a proper Thread that got its _state attribute assigned inside __init__ of the ThreadPool. In this __init__, when self._worker_handler is initialized, it gets back a proper Thread object on which we set the _state attribute to RUN, but when we then call current_thread, we don't get the object but _MainThread, so the state is not there.

**Comment by karthikvadla** [comment]
@booxter @julkiewicz You guys found any fix for above. 
I'm using 
- python (2.7.13)
- eventlet (0.18.2)
- gunicorn (19.7.1) 
- gevent (1.2.2)

I have celery task  which makes call to some other non-celery task. 
Then throws below.

```
[2017-12-09 20:34:33,404: WARNING/MainProcess] Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 325, in _handle_workers
    while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
AttributeError: '_MainThread' object has no attribute '_state'
[2017-12-09 20:34:33,498: WARNING/MainProcess] Exception in thread Thread-113:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 325, in _handle_workers
    while thread._state == RUN or (pool._cache and thread._state != TERMINATE):
AttributeError: '_MainThread' object has no attribute '_state'
```

**Comment by LingxianKong** [comment]
I met with the same problem in openstack, when using kubernetes python client(which is using multiprocessing.pool to send api request) in an oslo service(which is based on eventlet)

**Comment by hoangphuocbk** [comment]
I also met the same error, when I use kubernetes python client in OpenStack, it raise problem in multiprocessing.

**Comment by temoto** [comment]
@smtakeda thank you for test code.

There are two problems:

* `multiprocessing.pool` uses `Queue.not_{empty,full}` which was not implemented in Eventlet. Simple to mock enough to make it work.
* `multiprocessing.pool` appends new attribute `_state` to `threading.Thread` objects it uses. For some reason, it then reads `thread._state` from an object it did not modify, so there is no _state attribute. Stupid patch of all `Thread` objects with new attribute does not work.

Maybe solution is to create "red" version of multiprocessing.pool module, where (unlike green patching) threading is forced to stdlib version. No working fix yet.

**Comment by hoangphuocbk** [comment]
@temoto I hope you can fix this issue asap. Thank you.

**Comment by jaketesler** [comment]
I was able to "fix" the Eventlet `_MainThread` issue by using a hacky workaround, see [here (Issue #172)](https://github.com/eventlet/eventlet/issues/172#issuecomment-379421165). 

The fix in the comment patches `current_thread()` to return the proper `threading.Thread` object after a call to `Eventlet.monkey_patch()`, which allows correct tracking of the added `_state` attribute.

**Comment by smtakeda** [comment]
Just update: with 0.23.0, the results look better but not complete (very close):

```
from multiprocessing.pool import ThreadPool
import time
import eventlet
eventlet.monkey_patch()

def run_this(idx):
    print('hello {0}-1'.format(idx))
    time.sleep(1)
    print('hello {0}-2'.format(idx))

pool = ThreadPool(10)

for idx in range(10):
    pool.apply_async(run_this, [idx])

pool.close()
pool.join()
```

```
>python test.py                                                                                                                                                                                                                                                                                                                                                      
hello 0-1
hello 1-1
hello 2-1
hello 3-1
hello 4-1
hello 5-1
hello 6-1
hello 7-1
hello 8-1
hello 9-1
hello 0-2
hello 1-2
hello 2-2
hello 3-2
hello 4-2
hello 5-2
hello 6-2
hello 7-2
hello 8-2
hello 9-2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/local/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 495, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 738, in _help_stuff_finish
    inqueue.not_empty.acquire()
AttributeError: 'Queue' object has no attribute 'not_empty'
```

Python 2.7.10. I have not tried a monkey patching on `multiprocessing.pool` yet.
