### ISSUE TITLE
testsuite from test -0.15.2; SKIP=170, errors=10, failures=1

### ISSUE THREAD

**Issue by idella** [eventlet/eventlet#151]
from an ebuild or from the source;

reduced some unhelpful lines to shorten slightly

```python
......E..........................
======================================================================
ERROR: Failure: ImportError (No module named MySQLdb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/tests/mysqldb_test_monkey_patch.py", line 2, in <module>
    import MySQLdb as m
ImportError: No module named MySQLdb

======================================================================
ERROR: test_ident (tests.patcher_test.GreenThreadWrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/tests/patcher_test.py", line 40, in tearDown
    super(ProcessBase, self).tearDown()
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/tests/__init__.py", line 184, in tearDown
    eventlet.sleep(0)
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/eventlet/greenthread.py", line 32, in sleep
    hub.switch()
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/eventlet/hubs/hub.py", line 293, in switch
    return self.greenlet.switch()
TestIsTakingTooLong: 1

```

then ditto for

ERROR: test_is_alive (tests.patcher_test.GreenThreadWrapper)
ERROR: test_is_daemon (tests.patcher_test.GreenThreadWrapper)
ERROR: test_join (tests.patcher_test.GreenThreadWrapper)
ERROR: test_name (tests.patcher_test.GreenThreadWrapper)
ERROR: test_import_patched_defaults (tests.patcher_test.ImportPatched)
ERROR: test_patch_a_module (tests.patcher_test.ImportPatched)
ERROR: test_boolean (tests.patcher_test.MonkeyPatch)
ERROR: test_server_connection_timeout_exception (tests.wsgi_test.TestHttpd)
 
then

```python
FAIL: test_import_patched_defaults (tests.patcher_test.ImportPatched)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2/tests/patcher_test.py", line 92, in test_import_patched_defaults
    assert 'GreenSocket' in lines[1], repr(output)
AssertionError: "base <module 'eventlet.green.socket' from '/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2-python2_7/lib/eventlet/green/socket.py'> <module 'urllib' from '/usr/lib64/python2.7/urllib.pyc'>\nnewmod <module 'base' from '/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/temp/python2.7/tmpOGqtV1_patcher_test/base.py'> <module 'eventlet.green.socket' from '/mnt/gen2/TmpDir/portage/dev-python/eventlet-0.15.2/work/eventlet-0.15.2-python2_7/lib/eventlet/green/socket.py'> <class 'socket._socketobject'>\n"

----------------------------------------------------------------------
Ran 607 tests in 94.339s

FAILED (SKIP=170, errors=10, failures=1)
```
'''python
work/eventlet-0.15.2 $ find  -name MySQLdb.py
./eventlet/green/MySQLdb.py
```

I cannot figure why it can't import its own module, but it doesn't.
Can you replicate? Do you require anything further?

**Comment by prometheanfire** [comment]
I don't have this issue with 0.17.1

**Comment by temoto** [comment]
Great, thanks for testing.
