### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by Arfrever** [eventlet/eventlet#191]
Eventlet 0.16.1 has 5 errors in test suite with Python 2.7. (More failures and errors with Python 3.*.)

```
======================================================================
ERROR: test_incomplete_headers_13 (tests.websocket_new_test.TestWebSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/tests/websocket_new_test.py", line 53, in test_incomplete_headers_13
    http.request("GET", "/echo", headers=headers)
  File "/usr/lib64/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/eventlet/green/socket.py", line 61, in create_connection
    raise error(msg)
error: [Errno -9] Address family for hostname not supported

======================================================================
ERROR: test_incomplete_headers_75 (tests.websocket_test.TestWebSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/tests/websocket_test.py", line 58, in test_incomplete_headers_75
    http.request("GET", "/echo", headers=headers)
  File "/usr/lib64/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/eventlet/green/socket.py", line 61, in create_connection
    raise error(msg)
error: [Errno -9] Address family for hostname not supported

======================================================================
ERROR: test_incomplete_headers_76 (tests.websocket_test.TestWebSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/tests/websocket_test.py", line 75, in test_incomplete_headers_76
    http.request("GET", "/echo", headers=headers)
  File "/usr/lib64/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/eventlet/green/socket.py", line 61, in create_connection
    raise error(msg)
error: [Errno -9] Address family for hostname not supported

======================================================================
ERROR: test_incorrect_headers (tests.websocket_test.TestWebSocket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/tests/websocket_test.py", line 45, in test_incorrect_headers
    http.request("GET", "/echo")
  File "/usr/lib64/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/eventlet/green/socket.py", line 61, in create_connection
    raise error(msg)
error: [Errno -9] Address family for hostname not supported

======================================================================
ERROR: test_server_connection_timeout_exception (tests.wsgi_test.TestHttpd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/tests/wsgi_test.py", line 239, in tearDown
    greenthread.kill(self.killer)
  File "/var/tmp/portage/dev-python/eventlet-0.16.1-r1000/work/eventlet-0.16.1/eventlet/greenthread.py", line 294, in kill
    g.throw(*throw_args)
TestIsTakingTooLong: 1

----------------------------------------------------------------------
Ran 521 tests in 144.906s

FAILED (SKIP=128, errors=5)
```

**Comment by temoto** [comment]
Errno -9 is very strange. Please, post output of `ip a ; ip link`

**Comment by Arfrever** [comment]
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.100/24 brd 192.168.0.255 scope global wlp4s0
       valid_lft forever preferred_lft forever
    inet6 fe80::21f:3cff:feab:7210/64 scope link 
       valid_lft forever preferred_lft forever
4: ip_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN group default 
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip6_vti0: <NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/tunnel6 :: brd ::
6: sit0: <NOARP> mtu 1480 qdisc noop state DOWN group default 
    link/sit 0.0.0.0 brd 0.0.0.0
7: ip6tnl0: <NOARP> mtu 1452 qdisc noop state DOWN group default 
    link/tunnel6 :: brd ::
8: ip6gre0: <NOARP> mtu 1448 qdisc noop state DOWN group default 
    link/gre6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp6s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
4: ip_vti0@NONE: <NOARP> mtu 1364 qdisc noop state DOWN mode DEFAULT group default 
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip6_vti0: <NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/tunnel6 :: brd ::
6: sit0: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default 
    link/sit 0.0.0.0 brd 0.0.0.0
7: ip6tnl0: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default 
    link/tunnel6 :: brd ::
8: ip6gre0: <NOARP> mtu 1448 qdisc noop state DOWN mode DEFAULT group default 
    link/gre6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
```

**Comment by temoto** [comment]
This was probably fixed long ago, please reopen if not.
