### ISSUE TITLE
Example from documentation fails with python 3

### ISSUE THREAD

**Issue by vikt0rs** [eventlet/eventlet#206]
The first example from official documentation - [1] - fails  with the following error:

```
Traceback (most recent call last):
  File "eventlet_test.py", line 8, in <module>
    from eventlet.green import urllib2
  File "/home/viktors/sandbox/eventlet/green/urllib2.py", line 14, in <module>
    ('urllib', urllib))
  File "/home/vsergeev/sandbox/eventlet/patcher.py", line 93, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
ImportError: No module named 'urllib2'
```

Python documentation tells, that urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error.

[1] http://eventlet.net/doc/index.html#eventlet-documentation

**Comment by vikt0rs** [comment]
@temoto should we care about this?

**Comment by temoto** [comment]
Yes, now examples in documentation should contain separate Python3 snippets like this:
```
import eventlet
# Python3
from eventlet.green.urllib import request
# Python2
from eventlet.green import urllib2 as request

request.urlopen(...)
```

**Comment by polyakoff** [comment]
Previous code snippet does not work
![image](https://cloud.githubusercontent.com/assets/5703395/22437300/34213a2a-e730-11e6-9071-2cfe88aea771.png)

**Comment by temoto** [comment]
I'm sorry this is how you found that Python IDE are fantasy unicorns. All things considered, it's just not the right language for this development approach.

That snippet works allright.

```
% ./venv-34/bin/python -c 'from eventlet.green.urllib import request ; request.urlopen' && echo ok
ok
% ./venv-27/bin/python -c 'from eventlet.green import urllib2 as request ; request.urlopen' && echo ok
ok
```

AFAIK as of now this applies to all IDEs. In general, you should not expect IDE results be the same as actual code execution.
