### ISSUE TITLE
multiprocessing compatibility

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#210]
eventlet introduces difference in semantics between socket (blocking) and underlying file descriptor (non-blocking). multiprocessing grabs raw file descriptors off socket objects, expecting fd-s to repeat socket blocking semantics, which they don't. Naturally, when multiprocessing tries to use fd-s later, it gets `EAGAIN`.
```
# {stdlib}/multiprocessing/connection.py
    def Pipe(duplex=True):
# ...
            s1, s2 = socket.socketpair()
            s1.setblocking(True)
            s2.setblocking(True)
            c1 = _multiprocessing.Connection(os.dup(s1.fileno()))
            c2 = _multiprocessing.Connection(os.dup(s2.fileno()))
            s1.close()
            s2.close()
```

Possible solutions:

* propagate blocking semantics to (proxy) file descriptors returned by green `socket.fileno()` -- this may not actually help, since multiprocessing needs OS level `os.dup()` and they too have to be blocking for multiprocessing but non-blocking for eventlet.
* special case green/multiprocessing -- whether to patch `Pipe()` or `Connection`?

Related issues:
https://github.com/eventlet/eventlet/issues/209
http://stackoverflow.com/questions/17222354/celery-worker-hangs-on-zeo-database-access-race-condition/17409398#17409398

Thanks to @imazor for reporting this issue and test code.
```
import eventlet
eventlet.monkey_patch()
import multiprocessing
multiprocessing.Manager().Queue()  # IOError EAGAIN
print('pass')
```

**Comment by imazor** [comment]
I dont know if this can help.
But looks like gevent have same issue:

http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing

**Comment by shettyritesh** [comment]
Hello,
Is there any solution to this. I am facing this issue too. My user story is to listen on a RabbitMQ using oslo messaging which in turn uses Eventlet. Once message is received i use ansible to process the request which uses multi processing. I get the exact same error as shown above.

**Comment by temoto** [comment]
@shettyritesh if that's a possible solution for you, patch multiprocessing stdlib or copy it into your virtualenv with something along these lines:

**WARNING: untested dirty hack ahead**

```
--- a/connection.py	2015-03-16 02:13:20.000000000 +0300
+++ b/connection.py	2015-03-16 02:33:39.000000000 +0300
@@ -3,11 +3,14 @@
         Returns pair of connection objects at either end of a pipe
         '''
         if duplex:
+            import eventlet.greenio.base
             s1, s2 = socket.socketpair()
-            s1.setblocking(True)
-            s2.setblocking(True)
-            c1 = _multiprocessing.Connection(os.dup(s1.fileno()))
-            c2 = _multiprocessing.Connection(os.dup(s2.fileno()))
+            fd1 = os.dup(s1.fileno())
+            fd2 = os.dup(s2.fileno())
+            eventlet.greenio.base.set_nonblocking(fd1)
+            eventlet.greenio.base.set_nonblocking(fd2)
+            c1 = _multiprocessing.Connection(fd1)
+            c2 = _multiprocessing.Connection(fd2)
             s1.close()
             s2.close()
         else:
```

**Comment by temoto** [comment]
Patch above is not an "official recommended solution", but rather a quick dirty workaround in case you really need it fast.

**Comment by shettyritesh** [comment]
This patch didn't work for me. i made changes to the 
To be clear the error i am getting is as below

/usr/lib/python2.7/multiprocessing/connection.py

2015-03-14 23:20:33,847 - root - ERROR - Error in executing playbook[Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/opt/stack/venv/lib/python2.7/site-packages/attis_server-1.0.0a1-py2.7.egg/attis/engine/contentprocessor.py", line 119, in runPlaybook
    pb.run()
  File "/opt/stack/venv/local/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/playbook/__init__.py", line 347, in run
    if not self._run_play(play):
  File "/opt/stack/venv/local/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/playbook/__init__.py", line 674, in _run_play
    self._do_setup_step(play)
  File "/opt/stack/venv/local/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/playbook/__init__.py", line 619, in _do_setup_step
    accelerate_port=play.accelerate_port,
  File "/opt/stack/venv/local/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/runner/__init__.py", line 1458, in run
    results = self._parallel_exec(hosts)
  File "/opt/stack/venv/local/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/runner/__init__.py", line 1349, in _parallel_exec
    job_queue = manager.Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 434, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

**Comment by temoto** [comment]
Yes, it was supposed to cure that exact error. It seemed like a viable idea, though I didn't test it. I'm sorry, can't help more today. Please, wait for working fix.

**Comment by Hansimov** [comment]
I encounter the same problem. Using `eventlet.monkey_patch(thread=False)` solves it.

**Comment by jacoblapenna** [comment]
Interesting symptoms I discovered the hard way: when the external process is started in the `if __name__ == "__main__"` block of my web app, everything works flawlessly. If the process is started from an event handler, stuff breaks. See my minimal reproducible example [here](https://github.com/jacoblapenna/Eventlet_Multiprocessing). Just comment/uncomment the respective code blocks in `app.py` for a working and non-working app. The non working symptom is hundreds of websocket connection attempts, almost all of them closed before a connection could be established with the client trying to revert to polling on every bad attempt.
