### ISSUE TITLE
Unhandled ZeroReturnError exception

### ISSUE THREAD

**Issue by xsuchy** [eventlet/eventlet#217]
I have OpenStack instance and it uset eventlet. I got this traceback:
```
...
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 495, in __iter__
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack     chunk = self.next()
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 511, in next
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack     chunk = self._resp.read(CHUNKSIZE)
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack   File "/usr/lib64/python2.7/httplib.py", line 567, in read
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack     s = self.fp.read(amt)
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack   File "/usr/lib64/python2.7/socket.py", line 380, in read
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack     data = self._sock.recv(left)
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack   File "/usr/lib/python2.7/site-packages/eventlet/green/OpenSSL/SSL.py", line 55, in read
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack     return self.fd.read(size)
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack ZeroReturnError
2015-03-25 09:35:26.088 17470 TRACE nova.api.openstack
```
According to the pyOpenSSL docs ZeroReturnError means that the SSL connection has been closed cleanly.
I assume that eventlet should catch this exception and do something. E.g. return empty string.

**Comment by temoto** [comment]
Thank you, I agree, we should hide this exception. Could you please post full traceback and/or some minimal code to reproduce the issue?

`python --version` and `pip freeze` would also help.

**Comment by temoto** [comment]
@xsuchy ping

**Comment by xsuchy** [comment]
The full traceback is (from little bit different situation):
```
2015-04-03 15:03:22.670 36439 ERROR nova.scheduler.filter_scheduler [req-8dff2068-2571-4695-b765-17272f5926c8 529253f11fb246b9993bf926c35f4db3 566a072fb1694950998ad191fee3833b] [instance: 2e699d3c-2b4c-4ee9-ac1a-acd4fe1fada3] Error from last host: fed-cloud12.cloud.fedoraproject.org (node fed-cloud12.cloud.fedoraproject.org): [u'Traceback (most recent call last):\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1328, in _build_instance\n    set_access_ip=set_access_ip)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 393, in decorated_function\n    return function(self, context, *args, **kwargs)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1740, in _spawn\n    LOG.exception(_(\'Instance failed to spawn\'), instance=instance)\n', u'  File "/usr/lib/python2.7/site-packages/nova/openstack/common/excutils.py", line 68, in __exit__\n    six.reraise(self.type_, self.value, self.tb)\n', u'  File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 1737, in _spawn\n    block_device_info)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py", line 2287, in spawn\n    admin_pass=admin_password)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py", line 2656, in _create_image\n    project_id=instance[\'project_id\'])\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/imagebackend.py", line 192, in cache\n    *args, **kwargs)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/imagebackend.py", line 383, in create_image\n    prepare_template(target=base, max_size=size, *args, **kwargs)\n', u'  File "/usr/lib/python2.7/site-packages/nova/openstack/common/lockutils.py", line 249, in inner\n    return f(*args, **kwargs)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/imagebackend.py", line 182, in fetch_func_sync\n    fetch_func(target=target, *args, **kwargs)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/utils.py", line 653, in fetch_image\n    max_size=max_size)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/images.py", line 78, in fetch_to_raw\n    max_size=max_size)\n', u'  File "/usr/lib/python2.7/site-packages/nova/virt/images.py", line 72, in fetch\n    image_service.download(context, image_id, dst_path=path)\n', u'  File "/usr/lib/python2.7/site-packages/nova/image/glance.py", line 342, in download\n    for chunk in image_chunks:\n', u'  File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 495, in __iter__\n    chunk = self.next()\n', u'  File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 511, in next\n    chunk = self._resp.read(CHUNKSIZE)\n', u'  File "/usr/lib64/python2.7/httplib.py", line 567, in read\n    s = self.fp.read(amt)\n', u'  File "/usr/lib64/python2.7/socket.py", line 380, in read\n    data = self._sock.recv(left)\n', u'  File "/usr/lib/python2.7/site-packages/eventlet/green/OpenSSL/SSL.py", line 55, in read\n    return self.fd.read(size)\n', u'ZeroReturnError\n']
```
I am afraid that I do not have smaller reproducer then "Install Openstack on CentOS7 and set endpoints to https" which would take you several days to set up :(

```
# rpm -q python
python-2.7.5-16.el7.x86_64
```

None python module is installed using pip. Everything comes from CentOS or OpenStackRDO yum repos. However:
```
# pip freeze                                                                                                              
Babel==0.9.6                                                                                                                                       
Beaker==1.5.4                                                                                                                                      
Cheetah==2.4.4                                                                                                                                     
Django==1.6.10                                                                                                                                     
Flask==0.10.1                                                                                                                                      
IPy==0.75                                                                                                                                          
Jinja2==2.7.3                                                                                                                                      
M2Crypto==0.21.1                                                                                                                                   
Mako==0.8.1                                                                                                                                        
Markdown==2.4.1                                                                                                                                    
MarkupSafe==0.11                                                                                                                                   
MySQL-python==1.2.3                                                                                                                                
Paste==1.7.5.1                                                                                                                                     
PasteDeploy==1.5.0                                                                                                                                 
Pillow==2.0.0                                                                                                                                      
PyPAM==0.5.0                                                                                                                                       
PyYAML==3.10                                                                                                                                       
Pygments==1.4                                                                                                                                      
Routes==1.13                                                                                                                                       
SQLAlchemy==0.9.7                                                                                                                                  
Tempita==0.5.1                                                                                                                                     
WSME==0.6                                                                                                                                          
WebOb==1.2.3                                                                                                                                       
WebTest==1.3.4                                                                                                                                     
Werkzeug==0.9.1                                                                                                                                    
alembic==0.4.2                                                                                                                                     
amqp==1.4.5                                                                                                                                        
amqplib==1.0.2
ansible==1.8.4
anyjson==0.3.3
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
boto==2.34.0
bunch==1.0.1
ceilometer==2014.1.2
chardet==2.0.1
cinder==2014.1.3
cliff==1.4.4
cmd2==0.6.4
configobj==4.7.2
configshell-fb==1.1.14
croniter==0.3.4
decorator==3.4.0
django-appconf==0.6
django-compressor==1.3
django-openstack-auth==1.1.5
dogpile.cache==0.5.5
dogpile.core==0.4.1
ecdsa==0.11
ethtool==0.8
eventlet==0.15.2
futures==2.1.6
glance==2014.1.3
glusterfs-api==3.6.0.29
greenlet==0.4.2
horizon==2014.1.3
html5lib==0.999
httplib2==0.7.7
iniparse==0.4
ipaddr==2.1.9
iso8601==0.1.10
itsdangerous==0.23
jsonpatch==1.2
jsonpath-rw==1.2.3
jsonpointer==1.0
jsonschema==2.3.0
keyring==5.0
keystone==2014.1.2.1
kitchen==1.1.1
kmod==0.1
kombu==2.5.16
lesscpy==0.9j
lockfile==0.9.1
lxml==3.2.1
msgpack-python==0.4.4
netaddr==0.7.5
netifaces==0.5
networkx==1.8.1
neutron==2014.1.3
nose==1.3.0
nova==2014.1.3
numpy==1.7.1
oauthlib==0.6.0
oslo.config==1.2.1
oslo.messaging==1.3.0.2
oslo.rootwrap==1.0.0
packstack==2014.1.1dev1280
paramiko==1.15.1
passlib==1.5.3
pbr==0.10.0
pecan==0.4.5
ply==3.4
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyOpenSSL==0.13.1
pyasn1==0.1.6
pycadf==0.5.1
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.8.2
pygpgme==0.3
pyliblzma==0.5.3
pymongo==2.5.2
pyparsing==1.5.6
pysendfile==2.0.0
pysnmp==4.2.5
python-ceilometerclient==1.0.10
python-cinderclient==1.0.9
python-dateutil==1.5
python-fedora==0.3.36
python-glanceclient==0.12.0
python-heatclient==0.2.12
python-keyczar==0.71c
python-keystoneclient==0.9.0
python-ldap==2.4.15
python-memcached==1.48
python-neutronclient==2.3.4
python-novaclient==2.17.0
python-swiftclient==2.1.0
python-troveclient==1.0.5
pytz==2012d
pyudev==0.15
pyxattr==0.5.1
qpid-python==0.28
repoze.lru==0.4
requests==1.1.0
rsa==3.1.1
rtslib-fb==2.1.50
scipy==0.12.1
seobject==0.1
sepolicy==1.1
simplegeneric==0.8
simplejson==3.3.3
singledispatch==3.4.0.2
six==1.6.1
slip==0.4.0
slip.dbus==0.4.0
sqlalchemy-migrate==0.9.2
sqlparse==0.1.11
stevedore==0.14
suds==0.4.1
swift==1.13.1
swift3==1.7.0
targetcli-fb==2.1.fb37
taskflow==0.3.21
urlgrabber==3.10
urllib3==1.5
urwid==1.1.1
versiontools==1.9.1
warlock==1.0.1
websockify==0.5.1
wsgiref==0.1.2
yum-metadata-parser==1.1.4
```

**Comment by xsuchy** [comment]
One more full traceback from different log. This one is better formated:
```
2015-04-03 12:33:46.266 45212 WARNING ceilometer.agent [-] Continue after error from image:
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent Traceback (most recent call last):
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/ceilometer/agent.py", line 90, in poll_and_publish
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     resources=source_resources or agent_resources,
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/ceilometer/image/glance.py", line 108, in get_samples
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     for image in self._iter_images(manager.keystone, cache):
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/ceilometer/image/glance.py", line 79, in _iter_images
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     cache['images'] = list(self._get_images(ksclient))
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/ceilometer/image/glance.py", line 55, in _get_images
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     client.images.list(filters={"is_public": False})))
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/v1/images.py", line 174, in paginate
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     images = self._list(url, "images")
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/common/base.py", line 53, in _list
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     resp, body = self.api.json_request('GET', url)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 266, in json_request
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     resp, body_iter = self._http_request(url, method, **kwargs)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 241, in _http_request
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     body_str = ''.join([chunk for chunk in body_iter])
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 495, in __iter__
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     chunk = self.next()
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/glanceclient/common/http.py", line 511, in next
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     chunk = self._resp.read(CHUNKSIZE)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib64/python2.7/httplib.py", line 567, in read
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     s = self.fp.read(amt)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib64/python2.7/socket.py", line 380, in read
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     data = self._sock.recv(left)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent   File "/usr/lib/python2.7/site-packages/eventlet/green/OpenSSL/SSL.py", line 55, in read
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent     return self.fd.read(size)
2015-04-03 12:33:46.266 45212 TRACE ceilometer.agent ZeroReturnError
```

**Comment by temoto** [comment]
Thank you.

**Comment by temoto** [comment]
Sorry to leave this issue open. Since eventlet has many `except ZeroReturnError` lines, it may be instance of exception identity as in #413 -- just a guess.
