### ISSUE TITLE
eventlet POpen unable to wrap pipe in python 3.4 when using universal_newlines

### ISSUE THREAD

**Issue by croxis** [eventlet/eventlet#243]
I'm using eventlet in a flask and socketio stack. I'm attempting to use Popen to execute a long running  program and stream the stdout using eventlet to readline() in a nonblocking way.

The following example code:
```python

from subprocess import PIPE
from eventlet.green.subprocess import Popen
p = Popen(['ls'], shell=False, stdout=PIPE, universal_newlines=True)
```
results in 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/croxis/src/mtgai/venv/lib/python3.4/site-packages/eventlet/green/subprocess.py", line 59, in __init__
    wrapped_pipe = greenio.GreenPipe(pipe, pipe.mode, bufsize)
AttributeError: '_io.TextIOWrapper' object has no attribute 'mode'
```

**Comment by temoto** [comment]
Thanks for bug report! Fix is merged in master 60bce42.
