### ISSUE TITLE
non-deterministic test failure: (AssertionError: CPU usage over limit)

### ISSUE THREAD

**Issue by anthraxx** [eventlet/eventlet#266]
I'm currently trying to package this for Arch Linux repositories, therefor it would be great if all tests are passing. I have seen this test several times failing in the issue tracker and it also looks like the automatic travis build itself fails pretty often because of this.

Would it be possible to either make it lot less sensitive or somehow easily skippable? We are also planning to continuously test for reproducibility of packages and a non deterministic test that very sensitively relies on the current "mood" of the machine is suboptimal :smile: 

I would highly appreciate it if you consider solving this problem somehow.

```
    ======================================================================
    FAIL: test_cpu_usage_after_bind (tests.zmq_test.TestUpstreamDownStream) zmq eats CPU after PUB socket .bind()
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/__init__.py", line 92, in wrapped
    return func(*a, **kw)
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/zmq_test.py", line 435, in test_cpu_usage_after_bind
    check_idle_cpu_usage(0.2, 0.1)
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/__init__.py", line 215, in check_idle_cpu_usage
    allowed_part * 100)
    AssertionError: CPU usage over limit: user 10% sys 2% allowed 10%

    ======================================================================
    FAIL: test_cpu_usage_after_pub_send_or_dealer_recv (tests.zmq_test.TestUpstreamDownStream)
    zmq eats CPU after PUB send or DEALER recv.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/__init__.py", line 92, in wrapped
    return func(*a, **kw)
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/zmq_test.py", line 454, in test_cpu_usage_after_pub_send_or_dealer_recv
    check_idle_cpu_usage(0.2, 0.1)
    File "/build/python-eventlet/src/eventlet-0.17.4-py2/tests/__init__.py", line 215, in check_idle_cpu_usage
    allowed_part * 100)
    AssertionError: CPU usage over limit: user 8% sys 2% allowed 10%
```

**Comment by temoto** [comment]
Yes, non-deterministic failures are trouble for many people, it's enough already. Thanks for bringing this up. I'll think of something better.

**Comment by temoto** [comment]
@anthraxx please, try recent master a236bd20b7f3a2ed15294eff38cebe965ca2c3f9 , should be fixed now.

**Comment by temoto** [comment]
@anthraxx ping
I think I haven't seen zmq related sporadic CPU usage failures for a while now.
Please reopen if you still experience this problem.
