### ISSUE TITLE
Eventlet + flask-socketio AssertionError: write() before start_response()

### ISSUE THREAD

**Issue by liuq** [eventlet/eventlet#269]
Using Eventlet 0.17.4 + flask-socketio it raises this exception in handle_one_response

This is the traceback:

```
  File "/Users/digaspero/Documents/Development/pms/lib/python3.5/site-packages/eventlet/wsgi.py", line 485, in handle_one_response
    write(b'')
  File "/Users/digaspero/Documents/Development/pms/lib/python3.5/site-packages/eventlet/wsgi.py", line 380, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()
```

**Comment by jstasiak** [comment]
Hey @liuq, is this the whole traceback? Could you provide sample code to reproduce this?

**Comment by liuq** [comment]
Hi, unfortunately it's hard for me to reproduce the sample code since it is part of a big web app.

This is the log just before and after the error:

[2015-12-09 10:59:20,110] INFO 83678 [engineio] socket.py:63 - [pome] - f08712daa30c4ff7a0e38bc31862ba88: Sending packet MESSAGE with 2/instance/5634dde71fe3f52bfc6bd805,["New solution",{"description":null,"name":"UD1-bis.sol","last_update":1449651560017.277,"cost":357.0,"_links":{"content":{"GET":"solutions/5667fb781fe3f546df5d96ef/files/content","POST":"solutions/5667fb781fe3f546df5d96ef/files/content"},"self":{"PUT":"solutions/5667fb781fe3f546df5d96ef","GET":"solutions/5667fb781fe3f546df5d96ef"}},"contributors":[{"name":"Luca Di Gaspero"}],"id":"5667fb781fe3f546df5d96ef","instance":{"name":"UD1","id":"5634dde71fe3f52bfc6bd805"},"rank":4,"user":{"_links":{"picture":{"GET":"users/5637588f1fe3f52d084f4d48/picture"}},"name":"Luca Di Gaspero","id":"5637588f1fe3f52d084f4d48"},"summary":"New solution for instance 'UD1' of problem 'Generalized Balanced Academic Curriculum', cost value 357.0"}]
[2015-12-09 10:59:20,110] INFO 83678 [socketio] server.py:177 - [pome] - emitting event "New solution" to all [/problem/56349af91fe3f52464a3f81a]
127.0.0.1 - - [09/Dec/2015 10:59:20] "POST /instances/5634dde71fe3f52bfc6bd805/solutions HTTP/1.1" 200 1009 0.131912
(83678) accepted ('127.0.0.1', 50528)
127.0.0.1 - - [09/Dec/2015 10:59:20] "GET /instances/5634dde71fe3f52bfc6bd805/solutions?sort=cost%2Clast_update HTTP/1.1" 206 3641 0.165759
[2015-12-09 10:59:30,891] INFO 83678 [engineio] socket.py:40 - [pome] - f08712daa30c4ff7a0e38bc31862ba88: Received packet PING with None
[2015-12-09 10:59:30,891] INFO 83678 [engineio] socket.py:63 - [pome] - f08712daa30c4ff7a0e38bc31862ba88: Sending packet PONG with None
Traceback (most recent call last):
  File "/Users/digaspero/Documents/Development/pms/lib/python3.5/site-packages/eventlet/wsgi.py", line 485, in handle_one_response
    write(b'')
  File "/Users/digaspero/Documents/Development/pms/lib/python3.5/site-packages/eventlet/wsgi.py", line 380, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()

127.0.0.1 - - [09/Dec/2015 10:59:48] "GET /socket.io/?EIO=3&transport=websocket&sid=2d4388a9fb5441c5a4937a9bcd4ba5e1 HTTP/1.1" 500 0 163.987894
[2015-12-09 10:59:55,896] INFO 83678 [engineio] socket.py:40 - [pome] - f08712daa30c4ff7a0e38bc31862ba88: Received packet PING with None
[2015-12-09 10:59:55,896] INFO 83678 [engineio] socket.py:63 - [pome] - f08712daa30c4ff7a0e38bc31862ba88: Sending packet PONG with None

**Comment by lolobosse** [comment]
Hey there,

same error as @liuq with the same version of `eventlet` (`eventlet (0.17.4)`).
The code is on [github](https://github.com/lolobosse/InstrumentationServer) already but is not trivial. The problem as I do not know where the bug happen, I do not really know how to simplify it.

I do have a log, maybe it helps:
```
Client disconnected
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/eventlet/wsgi.py", line 485, in handle_one_response
    write(b'')
  File "/Library/Python/2.7/site-packages/eventlet/wsgi.py", line 380, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()
```

**Comment by temoto** [comment]
wsgi has seen big rewrites since then. Please reopen if you still experience this problem.

**Comment by skortchmark9** [comment]
Hi, I'm also experiencing this issue (when the client disconnects) with eventlet 0.20.0

**Comment by temoto** [comment]
Please, try again with latest code.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by skortchmark9** [comment]
Fixed in eventlet 0.21.0! Thanks!

**Comment by Divide-By-0** [comment]
I get this other error on local machine without gunicorn or nginx.

These are the relevant subset of my requirements:
```
sentry_sdk == 0.14.3
Flask_SocketIO == 4.2.1
eventlet == 0.25.1
```

This is my flask-socketio code on the server side:
```
socketio = SocketIO(engineio_logger=True, logger=True, debug=True, cors_allowed_origins="*", path='/socket.io')
...
socketio.init_app(app, async_mode="eventlet")
```

And this is my React socket io code on the client side:
```
          this.socket = io.connect(`http://localhost:5000?info=${someInfo}`, {
            transports: ['websocket', 'polling'] // an attempt to keep polling as a fallback but start on websockets
          });
```
Let me know if this helps. On Ubuntu the error looks like the above one, and locally on Windows it looks like this, when I refresh the react page. Notably the leave method on 
```Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 599, in handle_one_response
    write(b'')
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 491, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 357, in __init__
    self.handle()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 390, in handle
    self.handle_one_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 466, in handle_one_request
    self.handle_one_response()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 609, in handle_one_response
    write(err_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 538, in write
    wfile.flush()
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 607, in write
    return self._sock.send(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\hubs\hub.py", line 461, in fire_timers
    timer()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 359, in __init__
    self.finish()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 732, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 784, in finish
    self.wfile.close()
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 607, in write
    return self._sock.send(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine```

**Comment by temoto** [comment]
@Divide-By-0 please explain "the leave method". Did you truncate first traceback?

**Comment by Divide-By-0** [comment]
By leave method I mean client disconnect. First traceback is this:
`Client disconnected <Request 'http://localhost:5000/socket.io/?customqueryparameter=customvalue&EIO=3&transport=websocket' [GET]> c811....n024`

**Comment by Divide-By-0** [comment]
> @Divide-By-0 please explain "the leave method". Did you truncate first traceback?

By leave method I mean client disconnect. First traceback is this:
Client disconnected <Request 'http://localhost:5000/socket.io/?customqueryparameter=customvalue&EIO=3&transport=websocket' [GET]> c811....n024

**Comment by temoto** [comment]
Did you remove any lines in first traceback?
