### ISSUE TITLE
green.subprocess is broken with python3.5

### ISSUE THREAD

**Issue by MarSoft** [eventlet/eventlet#271]
Seems that it relies on `subprocess.mswindows` to determine current platform, but that variable (which is undocumented) was renamed in python 3.5: https://api.asm.skype.com/s/i?0-weu-d3-f7ed3534b987733bff86cea08fab4e21
It is advised to use other determining ways like `sys.platform == 'win32'`.
```
Python 3.5.0 (default, Sep 20 2015, 11:28:25)
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eventlet.green import subprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/eventlet/green/subprocess.py", line 41, in <module>
    class Popen(subprocess_orig.Popen):
  File "/usr/lib/python3.5/site-packages/eventlet/green/subprocess.py", line 49, in Popen
    if not subprocess_orig.mswindows:
AttributeError: module 'subprocess' has no attribute 'mswindows'
>>>
```

**Comment by temoto** [comment]
Jakub Stasiak has fixed it in commit da7f9732b6d9d52c8bca5cdbb536beb1fac14b44
it's in master.
