### ISSUE TITLE
HTTPS/SSL hangs when using requests library on Python 3.4

### ISSUE THREAD

**Issue by odlbo** [eventlet/eventlet#276]
Hello!
This bug appears when I'm trying to download some files.
Please, check my example bellow to reproduce the problem.

```python
>>> import eventlet
>>> import requests
>>> 
>>> requests.get('https://telegram.dev.drweb.com/static/test_file', timeout=20).status_code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/sessions.py", line 608, in send
    r.content
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/andy/venv/X3/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/home/andy/venv/X3/lib/python3.4/site-packages/eventlet/green/ssl.py", line 219, in recv_into
    timeout_exc=timeout_exc('timed out'))
  File "/home/andy/venv/X3/lib/python3.4/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/home/andy/venv/X3/lib/python3.4/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
```

If eventlet is not imported, I don't get this bug:
```python
>>> import requests
>>> 
>>> requests.get('https://telegram.dev.drweb.com/static/test_file', timeout=20).status_code
200
```

PS:
python version 3.4.0
eventlet==0.17.4
requests==2.9.0

**Comment by jstasiak** [comment]
Hey @odlbo, I believe this is addressed in https://github.com/eventlet/eventlet/pull/277, would you mind installing eventlet from the master branch from GitHub and testing again?

**Comment by odlbo** [comment]
Yep, you are right! It works with code from master branch.
Thank you!

**Comment by jstasiak** [comment]
Thank you @odlbo, I'll close this issue then.
