### ISSUE TITLE
Pipe Broken

### ISSUE THREAD

**Issue by jackmullen2** [eventlet/eventlet#284]
I am using flask and eventlet as the server .. I set up flask to "serve from directory" with "as_attachment=True" -- here is the route 
@app.route('/static/media/<directory>/<filename>')
def download_file_media(directory,filename):
    return send_from_directory('static/media/'+directory,
                               filename, as_attachment=True)

When a device .. like an iphone or computer using quicktime attempts to access a file ( a playable mp3 say) after a period of time I get an exception that is always repeatable :  (any help would be appreciated).. The flask implementation is also using flask-socketio and flask version is 1.0 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 477, in handle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/usr/lib/python2.7/socket.py", line 334, in writelines
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 376, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 32] Broken pipe

**Comment by temoto** [comment]
That error means client got disconnected. There's nothing you could do for recovery except reconnect on client side. Mobile devices connections are much more unstable, thus higher chance to get `EPIPE`. Consider it normal.

This issue is resolved when `eventlet.wsgi` produces human readable error message for such cases.

**Comment by tb2johm** [comment]
I'm running Python 3, and I'm not totally sure that I have the same version as the Issue creator.

Anyways, as I understand the code this exception is more or less supposed to be handled...
We get here from `handle_one_request()` where the last thing the code does is to call `self.handle_one_response()`. This call is surrounded by a try-except that would suppress any `socket.errors` with numbers in `BROKEN_SOCK`.

However in the `handle_one_response` when sending, the code has it's own exception handler. But this time the code doesn't except any `socket.error`.
