### ISSUE TITLE
TypeError: an integer is required (socket, sendto)

### ISSUE THREAD

**Issue by dianaclarke** [eventlet/eventlet#291]
I get the following error when I upgrade from eventlet 0.17.4 to 0.18.0.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/diana/envs/nova/lib/python2.7/site-packages/eventlet/greenio/base.py", line 380, in sendto
    return self._send_loop(self.fd.sendto, data, address, flags)
  File "/Users/diana/envs/nova/lib/python2.7/site-packages/eventlet/greenio/base.py", line 364, in _send_loop
    return send_method(data, *args)
TypeError: an integer is required
```

Which is related to the "Handle blocking I/O errors in GreenSocket" changes:

- Issue: ["Handle blocking I/O errors in GreenSocket"](https://github.com/eventlet/eventlet/issues/274)
- Commit: https://github.com/eventlet/eventlet/commit/bc4d1b5d362e5baaeded35b1e339b9db08172dd2

**Before:**

```
(nova)$ pip freeze | grep eventlet
eventlet==0.17.4

(nova)$ python
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> sock.sendto('', ('127.0.0.1', 22))
0
```
**After:**

```
(nova)$ pip install eventlet==0.18.0

(nova)$ python
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> sock.sendto('', ('127.0.0.1', 22))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/diana/envs/nova/lib/python2.7/site-packages/eventlet/greenio/base.py", line 380, in sendto
    return self._send_loop(self.fd.sendto, data, address, flags)
  File "/Users/diana/envs/nova/lib/python2.7/site-packages/eventlet/greenio/base.py", line 364, in _send_loop
    return send_method(data, *args)
TypeError: an integer is required
```

**Comment by jstasiak** [comment]
Hey, sorry about that. Fixed in master in https://github.com/eventlet/eventlet/commit/a79c0ee57af25ab176e34ae7ceb27a1c0262ae5d, we should do a bugfix release once the subprocess issue is sorted out too.

**Comment by temoto** [comment]
Reopen if needed.

**Comment by dianaclarke** [comment]
Oh, wow! That was fast. Thanks @jstasiak & @temoto!
