### ISSUE TITLE
eventlet 0.18.3 broke an unit test of OpenStack Neutron

### ISSUE THREAD

**Issue by haypo** [eventlet/eventlet#301]
The change 40714b1ffadd47b315ca07f9b85009448f0fe63d introduced a regression.

```
Traceback (most recent call last):
  File "/opt/stack/new/neutron/.tox/dsvm-functional-constraints/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/opt/stack/new/neutron/.tox/dsvm-functional-constraints/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "neutron/agent/linux/utils.py", line 381, in __init__
    server)
  File "/usr/lib/python2.7/SocketServer.py", line 647, in __init__
    self.setup()
  File "/opt/stack/new/neutron/.tox/dsvm-functional-constraints/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 306, in setup
    conn.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, True)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 95] Operation not supported
```

The code should maybe ignore socket.error, since it's more an optimization, no?

Neutron bug report:
https://bugs.launchpad.net/neutron/+bug/1546506

**Comment by HenryGessau** [comment]
What is the goal of disabling the nagle algorithm? The nagle algorithm is usually a good thing, The problem (of there is one) might instead be ACK delays. See [1]. Animats is John Nagle himself.

[1] https://news.ycombinator.com/item?id=10607422

**Comment by temoto** [comment]
@haypo Yes. Temporary fix: `eventlet.wsgi.HttpProtocol.disable_nagle_algorithm = False`
@HenryGessau Thank you very much. I didn't know that.

**Comment by temoto** [comment]
@haypo do you see this error only on UNIX sockets?

**Comment by cubeek** [comment]
I tested https://github.com/eventlet/eventlet/commit/ba4fddbb9c5f8f5edf0d2c8dcb350385e395a93a and it solves the issue in OpenStack Neutron.

**Comment by temoto** [comment]
Thanks. v0.18.4 contains fix. Have a nice day.
