### ISSUE TITLE
Too many PIPEs are created when subprocess.Open fails 

### ISSUE THREAD

**Issue by hunters1094** [eventlet/eventlet#307]
Hi

I'm running neutron-openvswitch-agent that uses eventlet to connect to ovs-vsctl via command line.
`def _subprocess_setup():
    # Python installs a SIGPIPE handler by default. This is usually not what
    # non-Python subprocesses expect.
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)

def subprocess_popen(args, stdin=None, stdout=None, stderr=None, shell=False,
                     env=None):
    return subprocess.Popen(args, shell=shell, stdin=stdin, stdout=stdout,
                            stderr=stderr, preexec_fn=_subprocess_setup,
                            close_fds=True, env=env)

obj = utils.subprocess_popen(cmd, shell=False,
                                     stdin=subprocess.PIPE,
                                     stdout=subprocess.PIPE,
                                     stderr=subprocess.PIPE,
                                     env=env)`

at weekend, when server runs on heavy load (I don't know exactly), the subprocess_popen throws Exception 

`Unable to execute ['ovs-vsctl', '--timeout=2', 'list-ports', 'br-int']. Exception: [Errno 11] Resource temporarily unavailable`

The obj object is not initialized. 

And the neutron-openvswitch-agent process gets too many open file (checked by lsof -p command). I see that, there are many created PIPE (about 700-800) and they are not deleted.

neutron-o 27964 openstack   10r  FIFO        0,8      0t0 2142890980 pipe
neutron-o 27964 openstack   11w  FIFO        0,8      0t0 2142890980 pipe
neutron-o 27964 openstack   12r  FIFO        0,8      0t0 2142890981 pipe
neutron-o 27964 openstack   13w  FIFO        0,8      0t0 2142890981 pipe
neutron-o 27964 openstack   14r  FIFO        0,8      0t0 2142890982 pipe
neutron-o 27964 openstack   15w  FIFO        0,8      0t0 2142890982 pipe
neutron-o 27964 openstack   16r  FIFO        0,8      0t0 2142890984 pipe
neutron-o 27964 openstack   17w  FIFO        0,8      0t0 2142890984 pipe
neutron-o 27964 openstack   18r  FIFO        0,8      0t0 2142890985 pipe

After 2 week, my neutron-openvswitch-agent process gets "Too many open files" error.

I guest that the stdin=subprocess.PIPE is created but not deleted when error. So, how can I handle the subprocess.PIPE?

Thank you

**Comment by temoto** [comment]
Please show all code where you use Popen `obj`.

**Comment by hunters1094** [comment]
Hi temoto

The code is from openstack neutron, in files: neutron/agent/linux/ovs_lib.py, neutron/agent/linux/utils.py, neutron/common/utils.py 

Every 2 second, neutron-openvswitch-agent runs 3 commands to check status of ovs-switchd. 
The commands are defined in neutron/agent/linux/ovs_lib.py:
`    def run_vsctl(self, args):
        full_args = ["ovs-vsctl", "--timeout=2"] + args
        try:
            return utils.execute(full_args, root_helper=self.root_helper)
        except Exception as e:
            LOG.error(_("Unable to execute %(cmd)s. Exception: %(exception)s"),
                      {'cmd': full_args, 'exception': e})`

The code use Popen:

`def execute(cmd, root_helper=None, process_input=None, addl_env=None,
            check_exit_code=True, return_stderr=False):
    if root_helper:
        cmd = shlex.split(root_helper) + cmd
    cmd = map(str, cmd)

    LOG.debug(_("Running command: %s"), cmd)
    env = os.environ.copy()
    if addl_env:
        env.update(addl_env)
    try:
        obj = utils.subprocess_popen(cmd, shell=False,
                                     stdin=subprocess.PIPE,
                                     stdout=subprocess.PIPE,
                                     stderr=subprocess.PIPE,
                                     env=env)
        _stdout, _stderr = (process_input and
                            obj.communicate(process_input) or
                            obj.communicate())
        obj.stdin.close()
        m = _("\nCommand: %(cmd)s\nExit code: %(code)s\nStdout: %(stdout)r\n"
              "Stderr: %(stderr)r") % {'cmd': cmd, 'code': obj.returncode,
                                       'stdout': _stdout, 'stderr': _stderr}
        LOG.debug(m)
        if obj.returncode and check_exit_code:
            raise RuntimeError(m)
    finally:
        # NOTE(termie): this appears to be necessary to let the subprocess
        #               call clean something up in between calls, without
        #               it two execute calls in a row hangs the second one
        greenthread.sleep(0)

    return return_stderr and (_stdout, _stderr) or _stdout`

The exception is: "Unable to execute ['ovs-vsctl', '--timeout=2', 'list-ports', 'br-int']. Exception: [Errno 11] Resource temporarily unavailable"

Thanks

**Comment by hunters1094** [comment]
The stacktrace when error:

2016-04-04 18:05:33.942 7817 ERROR neutron.agent.common.ovs_lib [req-42b082b1-2fbf-48a2-b2f3-3b7d774141f0 - - - - -] Unable to execute ['ovs-ofctl', 'dump-flows', 'br-int', 'table=23']. Exception: [Errno 11] Resource temporarily unavailable
2016-04-04 18:05:33.944 7817 ERROR neutron.agent.common.ovs_lib [req-42b082b1-2fbf-48a2-b2f3-3b7d774141f0 - - - - -] Traceback (most recent call last):
  File "/home/hunters/neutron-7.0.0/neutron/agent/common/ovs_lib.py", line 226, in run_ofctl
    process_input=process_input)
  File "/home/hunters/neutron-7.0.0/neutron/agent/linux/utils.py", line 120, in execute
    addl_env=addl_env)
  File "/home/hunters/neutron-7.0.0/neutron/agent/linux/utils.py", line 89, in create_process
    stderr=subprocess.PIPE)
  File "/home/hunters/neutron-7.0.0/neutron/common/utils.py", line 199, in subprocess_popen
    close_fds=close_fds, env=env)
  File "/home/hunters/neutron-7.0.0/.venv/local/lib/python2.7/site-packages/eventlet/green/subprocess.py", line 53, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable

**Comment by hunters1094** [comment]
Hi

Maybe it relates to this bug of python. https://bugs.python.org/issue21619

**Comment by temoto** [comment]
Thank you, we can easily copy EPIPE ignore to green subprocess.
