### ISSUE TITLE
green package (more than one module level) weirdness

### ISSUE THREAD

**Issue by jstasiak** [eventlet/eventlet#316]
Extracted from https://github.com/eventlet/eventlet/issues/267#issuecomment-204391271

A minimal code to reproduce (latest Eventlet and httplib2, Python 3.5.1):

```python
import httplib2
import eventlet.green.urllib

http = httplib2.Http()
http.request('http://example.org')
```

The result:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(http.request('http://example.org'))
  File "/Users/me/ve/35/lib/python3.5/site-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/me/ve/35/lib/python3.5/site-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/me/ve/35/lib/python3.5/site-packages/httplib2/__init__.py", line 1047, in _conn_request
    response = Response(response)
  File "/Users/me/ve/35/lib/python3.5/site-packages/httplib2/__init__.py", line 1382, in __init__
    for key, value in info.items():
AttributeError: 'HTTPResponse' object has no attribute 'items'
```

The relevant bit of code from ``httplib2/__init__.py``:

```python
        if isinstance(info, http.client.HTTPResponse):  # <- this condition fails although it should not
            for key, value in info.getheaders():
                key = key.lower()
                prev = self.get(key)
                if prev is not None:
                    value = ', '.join((prev, value))
                self[key] = value
            self.status = info.status
            self['status'] = str(self.status)
            self.reason = info.reason
            self.version = info.version
        elif isinstance(info, email.message.Message):
            for key, value in list(info.items()):
                self[key.lower()] = value
            self.status = int(self['status'])
        else:
            for key, value in info.items():  # <- the first condition doesn't match so this is executed and fails
                self[key.lower()] = value
            self.status = int(self.get('status', self.status))
```

I think that's because existing, already imported ``http.client`` module is indirectly replaced when ``eventlet.green.urllib`` is imported and this breaks things that already saw the original ``http.client`` module, see this:

```python
import http.client
print(['before green import', id(http.client)])
import eventlet.green.urllib
print(['after green import', id(http.client)])
```

The result:
```
['before green import', 4491451592]
['after green import', 4500059704]
```

**Comment by jstasiak** [comment]
Another example of this (Eventlet fb067b6). See ``eventlet.support.greendns.HostsAnswer`` class definition:

```python
# ...
class HostsAnswer(dns.resolver.Answer):
    """Answer class for HostsResolver object"""
# ...
```

Minimal test case:

```python
# t.py
from __future__ import print_function

from eventlet.support import greendns

import sys
if sys.argv[1] == 'yes':
    import dns.resolver


print(sys.argv[1], issubclass(greendns.HostsAnswer, greendns.dns.resolver.Answer))
```

```
# Python 2.7
% python t.py yes
yes False
% python t.py no 
no True

# Python 3.5.1
% python t.py yes
yes False
% python t.py no 
no True
```
