### ISSUE TITLE
'_DummyThread' object has no attribute '_children'" using Billiard

### ISSUE THREAD

**Issue by yrik** [eventlet/eventlet#345]
When I do monkey patch and trying to use Billiard it seems broke their pool implementation.
Plase advice how to handle it.

What I'm trying to do:
- to run Celery with prefork concurrency model and patch django to use eventlet code in the celery task.

Here is full traceback

```

[2016-09-06 07:00:12,836: DEBUG/MainProcess] | Worker: Starting Pool
[2016-09-06 07:00:12,850: ERROR/MainProcess] Unrecoverable error: AttributeError("'_DummyThread' object has no attribute '_children'",)
Traceback (most recent call last):
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 119, in on_start
    **self.options)
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/billiard/pool.py", line 976, in __init__
    self._worker_handler.start()
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/billiard/pool.py", line 491, in start
    super(PoolThread, self).start(*args, **kwargs)
  File "/home/skout/skout_main/.env/local/lib/python2.7/site-packages/billiard/dummy/__init__.py", line 71, in start
    self._parent._children[self] = None
AttributeError: '_DummyThread' object has no attribute '_children'

```

**Comment by temoto** [comment]
I think possible solutions:
* monkey_patch before importing billiard
* reimport billiard modules after patch
