### ISSUE TITLE
Freebsd eventlet abort error causing the webapp not to accept anymore connections

### ISSUE THREAD

**Issue by christopher-abastar** [eventlet/eventlet#355]
Hi,

I tried running this with gunicorn.  Upon stumbling on this error, eventlet seems stops accepting new connections.  Anyone know what to do to recover?
```sh
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/semaphore.py", line 145, in _do_acquire
    waiter.switch()
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/home/vf/env/lib/python3.5/site-packages/gunicorn/workers/geventlet.py", line 52, in _eventlet_serve
    conn, addr = sock.accept()
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/greenio/base.py", line 212, in accept
    res = socket_accept(fd)
  File "/home/vf/env/lib/python3.5/site-packages/eventlet/greenio/base.py", line 54, in socket_accept
    return descriptor.accept()
  File "/usr/local/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
ConnectionAbortedError: [Errno 53] Software caused connection abort
```

**Comment by temoto** [comment]
Can you teach me how to reproduce it? `uname -a` could also help.

**Comment by instasck** [comment]
I have exactly the same !

Having Flask app
````

# start flask
app = Flask(__name__)
setup_logging(app, level=logging.INFO)   # <= add this line

api = Api(app)
api.add_resource(CrmStatus, '/get_crm_status')  #
````

````

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.9/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 82, in _eventlet_serve
    conn, addr = sock.accept()
  File "/usr/local/lib/python3.9/site-packages/eventlet/greenio/base.py", line 224, in accept
    res = socket_accept(fd)
  File "/usr/local/lib/python3.9/site-packages/eventlet/greenio/base.py", line 61, in socket_accept
    return descriptor.accept()
  File "/usr/local/lib/python3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
ConnectionAbortedError: [Errno 103] Software caused connection abort
Removing descriptor: 5

````
````
services:
  crm_proxy:
    build: .
    container_name: crm_proxy
    image: crm_proxy
    # workers must be only 1 since we use locks
    command: >
      **bash -c "gunicorn --bind 0.0.0.0:15000 wsgi_crm_proxy:app --workers 1 --timeout 60 --graceful-timeout 60 --worker-class eventlet --thread 1 --worker-connections=1000 --log-level debug"**
    restart: unless-stopped
    stop_signal: SIGQUIT
    stop_grace_period: 120s   # >= your gunicorn --graceful-timeout (60s)
    ports:
      - "15000:15000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - LOG_DIR=/app/logs        # 👈 ensures your app knows where to log
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs         # 👈 mount local logs directory into container
````

it is getting stuck forever. happen really rear. I have like 10 services with those configurations and only 2-3 services experience it.

**Comment by itamarst** [comment]
Note that:

> Eventlet now follows a new maintenance policy. Only maintenance for stability and bug fixing will be provided. No new features will be accepted, except those related to the asyncio migration. Usages in new projects are discouraged. Our goal is to plan the retirement of eventlet and to give you ways to move away from eventlet.

FreeBSD support is outside the scope of what we can support; at best we can have it use the select() hub by default. As a workaround:

```
export EVENTLET_HUB=selects
```

will do that. It won't scale as well, though. And since this is probably a new project: don't use eventlet.
