### ISSUE TITLE
Monkey patching causes Eventlet to raise ssl.SSLError for certain domains

### ISSUE THREAD

**Issue by joestepp** [eventlet/eventlet#360]
Basic GET requests to certain domains always fail after `eventlet.monkey_patch()` is called. Here's an example:

Python 3.5.2
eventlet 0.19.0
requests 2.12.3

```
>>> import requests
>>> import eventlet
>>> eventlet.monkey_patch()
>>> requests.get('https://httpbin.org/', timeout=30)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/models.py", line 703, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/eventlet/green/ssl.py", line 224, in recv_into
    timeout_exc=timeout_exc('timed out'))
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/Users/joestepp/.virtualenvs/read_timeout/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
```

This happens on every GET to httpbin.com, but not to other domains such as google.com or yahoo.com, curiously. We originally noticed this when querying Front's API. Not monkey patching causes the request to succeed. It seems like this is related to [276.](https://github.com/eventlet/eventlet/issues/276)

**Comment by joestepp** [comment]
It appears that the monkey-patching of `socket` in particular is what's causing this issue (which might be obvious from the traceback):

```
In [1]: import requests
In [2]: import eventlet
In [3]: eventlet.monkey_patch(os=True, thread=True, time=True, psycopg=True)
In [4]: requests.get('https://httpbin.org/', timeout=30)
Out[4]: <Response [200]>
```

Only patching `socket` also causes the error:

```
In [1]: import requests
In [2]: import eventlet
In [3]: eventlet.monkey_patch(socket=True)
In [4]: requests.get('https://httpbin.org/', timeout=30)
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
...
```

When `socket` is monkey-patched, requests to https://httpbin.org/ always fail. Requests to 
https://api2.frontapp.com/ fail randomly (not just by querying the root domain, but when we actually make an authorized request at various endpoints). Requests to https://google.com and https://yahoo.com never fail.

This is a serious issue for us as we use `eventlet` with our Gunicorn and Celery workers, and outgoing requests from both are running into this issue. We're a fairly large operation so we get a few dozen errors a day due to this. A fix for this would be very appreciated. Thanks!

**Comment by temoto** [comment]
Please, try latest master. We have at least 2 major changes related to SSL.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by joestepp** [comment]
@temoto This resolved the issue. Thank you very much!

**Comment by chengshifan** [comment]
In my case , I just put 
```
import eventlet
eventlet.monkey_patch()
```
on the head of py , and then import other libraries.
