### ISSUE TITLE
python3.6 socket_test.test_dns_methods_are_green fails on poll/epolls hub

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#374]
Python3.6 continues to bring new exciting test failures, I guess it's good because they clearly are changing a lot of internals untouched for years.

This blocks v0.21 release.

```
tests.socket_test.test_dns_methods_are_green ... Program /Users/temoto/dev/github.com/eventlet/eventlet/tests/isolated/socket_resolve_green.py output:
---
Traceback (most recent call last):
  File "/Users/temoto/dev/github.com/eventlet/eventlet/tests/isolated/socket_resolve_green.py", line 41, in <module>
    assert 0.1 <= td < 0.3, 'Resolve time expected: ~0.1s, real: {0:.3f}'.format(td)
AssertionError: Resolve time expected: ~0.1s, real: 0.497

---
FAIL

======================================================================
FAIL: tests.socket_test.test_dns_methods_are_green
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/temoto/dev/github.com/eventlet/eventlet/venv-36/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/temoto/dev/github.com/eventlet/eventlet/tests/socket_test.py", line 75, in test_dns_methods_are_green
    tests.run_isolated('socket_resolve_green.py', pythonpath_extend=[mock_sys_pkg_dir])
  File "/Users/temoto/dev/github.com/eventlet/eventlet/tests/__init__.py", line 359, in run_isolated
    run_python(prefix + path, **kwargs)
  File "/Users/temoto/dev/github.com/eventlet/eventlet/tests/__init__.py", line 352, in run_python
    assert ok, 'Expected single line "pass" in stdout'
AssertionError: Expected single line "pass" in stdout

----------------------------------------------------------------------
```

**Comment by temoto** [comment]
Okay this sporadic test failure is fixed in master 0fed9e52ed84f690cd20495375fc06203889f189

But it revealed a problem with GreenPool slow first `.spawn()` that is not fixed as of 2017-01-18: #379
