### ISSUE TITLE
no EAI_NODATA def in FreeBSD socket impl

### ISSUE THREAD

**Issue by dirkye** [eventlet/eventlet#393]
Hi, all,

I have installed eventlet via pip in my FreeBSD:

uname -a =>
FreeBSD xxx.xxx.com 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11 #0: Mon Oct 24 18:49:24 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

pip list | grep eventlet =>
eventlet (0.20.1)

There will be error when import eventlet in python:

Python 2.7.13 (default, Jan 10 2017, 11:30:54) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python2.7/site-packages/eventlet/convenience.py", line 6, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python2.7/site-packages/eventlet/green/socket.py", line 28, in <module>
    from eventlet.support import greendns
  File "/usr/local/lib/python2.7/site-packages/eventlet/support/greendns.py", line 82, in <module>
    EAI_NODATA_ERROR = socket.gaierror(socket.EAI_NODATA, 'No address associated with hostname')
AttributeError: 'module' object has no attribute 'EAI_NODATA'
>>>

**Comment by temoto** [comment]
Link to same issue in upstream CPython: https://bugs.python.org/issue25138

It was removed from FreeBSD in 2003 :-)
https://lists.freebsd.org/pipermail/freebsd-ports/2003-October/005757.html

They say proper fix is to replace `EAI_NODATA` with `EAI_NONAME`.

**Comment by temoto** [comment]
Please, try this patch

`pip install https://github.com/eventlet/eventlet/archive/eainodata-393.zip`

**Comment by dirkye** [comment]
Hi, temoto,

Thanks very much.

It's can import in python now =>

Python 2.7.13 (default, Jan 10 2017, 15:16:09) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> eventlet.version_info
(0, 20, 1)
>>> 

But it still fail in my celery daemon =>

[2017-02-25 21:46:27,533: CRITICAL/MainProcess] Unrecoverable error: RuntimeError('no suitable implementation for this system',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_start
    self.emit_banner()
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 158, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python2.7/site-packages/celery/apps/worker.py", line 223, in startup_info
    platform=safe_str(_platform.platform()),
  File "/usr/local/lib/python2.7/platform.py", line 1604, in platform
    bits,linkage = architecture(sys.executable)
  File "/usr/local/lib/python2.7/platform.py", line 1066, in architecture
    output = _syscmd_file(executable, '')
  File "/usr/local/lib/python2.7/platform.py", line 1009, in _syscmd_file
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python2.7/site-packages/eventlet/green/subprocess.py", line 55, in __init__
    subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
  File "/usr/local/lib/python2.7/subprocess.py", line 420, in __init__
    self.stdout = os.fdopen(c2pread, 'rb', bufsize)
  File "/usr/local/lib/python2.7/site-packages/eventlet/green/os.py", line 28, in fdopen
    return greenio.GreenPipe(fd, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenio/py2.py", line 41, in __init__
    super(GreenPipe, self).__init__(_SocketDuckForFd(fileno), mode, bufsize)
  File "/usr/local/lib/python2.7/site-packages/eventlet/greenio/py2.py", line 128, in __init__
    notify_opened(fileno)
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 189, in notify_opened
    hub = get_hub()
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 42, in get_default_hub
    import eventlet.hubs.kqueue
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/kqueue.py", line 8, in <module>
    from eventlet.hubs.hub import BaseHub, READ, WRITE, noop
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/usr/local/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
Exception AttributeError: "'_SocketDuckForFd' object has no attribute '_closed'" in <bound method _SocketDuckForFd.__del__ of _SocketDuckForFd:6> ignored

Thanks again.

**Comment by temoto** [comment]
Okay, fix is merged into master 4e775e2

About latter error, you may wish to subscribe to issue #394
