### ISSUE TITLE
Weird behavior when a greenthread is trying to join itself

### ISSUE THREAD

**Issue by egorf** [eventlet/eventlet#400]
Hi!

I know this is not exactly a very common scenario, but still it does not mimic the standard library and might cause trouble, as `join()` practically becomes `terminate()`.

```
import eventlet
eventlet.monkey_patch()
import threading

class Hey(object):

    def __init__(self):
        self.thread = threading.Thread(target=self.kill)
        self.thread.start()

    def kill(self):
        print("Join")
        self.thread.join()
        print("Done")

h = Hey()
```

If I comment the monkey_patch command at the top, join will throw a `RuntimeError`:
```
Join
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tests/eventlet_test.py", line 13, in kill
    self.thread.join()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

However, with the patch, the script will finish just printing this:

```
Join
```

**Comment by temoto** [comment]
HTTP 400 - Bad Request. :-)

Seriously, what are you trying to achieve with this?

**Comment by egorf** [comment]
@temoto 
I've probably oversimplified the example. Here's a use case for this:

Say, I'm using the Observer pattern. In this case, Collector is the observer and DataProvider is a subject to observe. Every time DataProvider comes up with new data, it notifies the Collector, calling its `update` method. Collector processes new data and checks if certain collection requirements are met. If they are, we accept the collected data and stop the DataProvider. Stopping the DataProvider means stopping its main activity thread. However, the `update` method is already called from inside this thread.

```
class Collector(observer_pattern.Observer):

    def __init__(self):
        super(Collector, self).__init__()
        self.data_provider = DataProvider()

    def start_collecting(self):
        self.data_provider.start_listening()
        self.subscribe_to_sample_collection(self)

    def stop_collecting(self):
        self.data_provider.stop_listening()
        self.unsubscribe_from_sample_collection(self)

    def subscribe_to_sample_collection(self, observer):
        self.data_provider.register_observer(observer)

    def unsubscribe_from_sample_collection(self, observer):
        self.data_provider.remove_observer(observer)

    def update(self, data_provider):
        self.process_new_data()

        if self.are_requirements_met():
            self.accept()

    def accept(self):
        self.stop_collecting()
        print("Accepted")

    def cancel(self):
        self.stop_collecting()
        print("Canceled")
```
