### ISSUE TITLE
Patching existing locks causes RLocks being acquired by different threads

### ISSUE THREAD

**Issue by tianquan23** [eventlet/eventlet#409]
For Python 2, patching existing locks replaces RLock._RLock__owner with currentthread ID no matter the old lock is locked or not and thus an unlocked RLock would have a non None owner (e.g. <_RLock owner=140106584489808 count=0>).
Then if we acquire the RLock in the same thread, the method RLock.acquire would not invoke the _RLock__block.acquire() since it treats this is a recursive acquire by checking current thread ID. And then the following RLock.release would invoke the _RLock__block.release method resulting in the counter of Semaphore being improved to 2. Thus, the RLock could be acquired by two dirrerent threads.

 ## How to reproduce:
### Code
```
import eventlet
from eventlet import greenpool
import threading

lock = threading.RLock()
eventlet.monkey_patch()

def task(a):
    with lock:
        print "[%s] Acquired lock" % a
        eventlet.sleep(1)
        print "[%s] Releasing lock" % a

# This will improve lock._RLock__block.couter to 2
lock.acquire()
lock.release()
print 'lock._RLock__block: %s' % lock._RLock__block

pool = greenpool.GreenPool()
pool.spawn(task, 'a')
pool.spawn(task, 'b')
pool.waitall()
```
### Output
```
lock._RLock__block: <Semaphore c=2 _w[0]>
[a] Acquired lock
[b] Acquired lock
[a] Releasing lock
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "test-lock2.py", line 12, in task
    print "[%s] Releasing lock" % a
  File "/usr/lib/python2.7/threading.py", line 216, in __exit__
    self.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
[b] Releasing lock
```

**Comment by temoto** [comment]
Fix was merged in master f72cc96a70f9e9d23fc6e00d994263829b672be0

Thank you. Have a great time.
