### ISSUE TITLE
error parsing resolv.conf search entries

### ISSUE THREAD

**Issue by eharney** [eventlet/eventlet#424]
My resolv.conf has the following:

$ cat /etc/resolv.conf 
search .domain.com e.localdomain
nameserver 192.168.50.1

This causes eventlet's resolv.conf parsing to fail, because it does not expect there to be a leading "." on "domain.com" in the search list.  I'm not sure if this format is correct, but it does work with standard system DNS libraries.

Changing ".domain.com" to "domain.com" makes things work.

Traceback (most recent call last):
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/unittest2/loader.py", line 490, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/eharney/src/cinder-review4/cinder/__init__.py", line 21, in <module>
    import eventlet  # noqa
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/__init__.py", line 15, in <module>
    from eventlet import convenience
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/convenience.py", line 6, in <module>
    from eventlet.green import socket
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/green/socket.py", line 28, in <module>
    from eventlet.support import greendns
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/greendns.py", line 335, in <module>
    resolver = ResolverProxy(hosts_resolver=HostsResolver())
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/greendns.py", line 299, in __init__
    self.clear()
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/greendns.py", line 302, in clear
    self._resolver = dns.resolver.Resolver(filename=self._filename)
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/dns/resolver.py", line 605, in __init__
    self.read_resolv_conf(filename)
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/dns/resolver.py", line 661, in read_resolv_conf
    self.search.append(dns.name.from_text(suffix))
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/dns/name.py", line 785, in from_text
    return from_unicode(text, origin, idna_codec)
  File "/home/eharney/src/cinder-review4/.tox/py34/lib/python3.4/site-packages/eventlet/support/dns/name.py", line 750, in from_unicode
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

**Comment by eharney** [comment]
This is with eventlet 0.20.0.

**Comment by temoto** [comment]
Let's try first to resolve issue in upstream library https://github.com/rthalley/dnspython to avoid code diverge if possible.
Please, copy-paste issue to them.

**Comment by temoto** [comment]
@eharney Please, try again with latest code. I've updated bundled dnspython to their latest version, maybe it's fixed.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`
