### ISSUE TITLE
monkey_patch is broken on CPython 2.7.13

### ISSUE THREAD

**Issue by antocuni** [eventlet/eventlet#428]
This small snippet is enough to crash:
```python
import eventlet
eventlet.monkey_patch()
print eventlet.listen(('localhost', 3500))
```

```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    print eventlet.listen(('localhost', 3500))
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/convenience.py", line 40, in listen
    sock = socket.socket(family, socket.SOCK_STREAM)
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 137, in __init__
    notify_opened(fd.fileno())
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 189, in notify_opened
    hub = get_hub()
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/home/antocuni/.virtualenvs/tmp/local/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

The culprit is this CPython's commit:
https://github.com/python/cpython/commit/eb063011ab6628d45cffab2f41947866b0d00e8d

this inserts a call to `subprocess` inside `ctypes.util.find_library`, which triggers the import cycle.
This affects CPython >= 2.7.13 and PyPy >= 5.3 (since from that version, it uses the stdlib of CPython 2.7.13)

Workarounds:
1. use `eventlet==0.20`

2. insert a call to `eventlet.sleep()` **before** calling `eventlet.monkey_patch()`

**Comment by temoto** [comment]
Thanks for detail on CPython change.

Please track the progress on this problem in #401
