### ISSUE TITLE
spurious "Connection reset by peer" errors in wsgi+ssl

### ISSUE THREAD

**Issue by stefannica** [eventlet/eventlet#446]
The following behavior has been observed in an openstack HA environment configured with SSL enabled and having an HAProxy instance running in front of the API services. All openstack API services which rely on eventlet are flooding /var/log/messages with errors of the form:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 734, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/eventlet/wsgi.py", line 339, in handle_one_request
    self.raw_requestline = self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/site-packages/eventlet/green/ssl.py", line 194, in recv
    return self._base_recv(buflen, flags, into=False)
  File "/usr/lib/python2.7/site-packages/eventlet/green/ssl.py", line 227, in _base_recv
    read = self.read(nbytes)
  File "/usr/lib/python2.7/site-packages/eventlet/green/ssl.py", line 139, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/eventlet/green/ssl.py", line 113, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib64/python2.7/ssl.py", line 673, in read
    v = self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

```
This is caused by the HAproxy health checker, which resets the TCP connection with a RST/ACK instead of going through the graceful connection close handshake.

The errors don't actually cause the API services to fail, they seem to be harmless in that respect. However, they do pollute the /var/log/messages file an awful lot, which makes them a nuisance.

**Comment by vuntz** [comment]
@stefannica can be closed, I guess?
