### ISSUE TITLE
socket.gethostbyname TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by scone** [eventlet/eventlet#460]
I ran into an error when performing a gethostbyname query for a specific domain, jk1l.ru (This may be malicious, don't visit it.).

I can't determine why bytes verses a string are being returned. 

python 3.5.2
eventlet (0.21.0)
greenlet (0.4.12)
gunicorn (19.7.1)

```
ERROR 2018-01-13 03:58:15,217 exception 25605 139667093169872 Internal Server Error: /check/
Traceback (most recent call last):
  File "/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/phishcheck/phishchecker/views.py", line 385, in check
    ip = socket.gethostbyname(hostname)
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 535, in gethostbyname
    rrset = resolve(hostname)
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 413, in resolve
    return _proxy.query(name, rdtype, raise_on_no_answer=raises)
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 371, in query
    return end()
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 350, in end
    raise result[1]
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 331, in step
    a = fun(*args, **kwargs)
  File "/env/lib/python3.5/site-packages/eventlet/support/dns/resolver.py", line 971, in query
    source_port=source_port)
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 779, in tcp
    ldata = _net_read(s, 2, expiration)
  File "/env/lib/python3.5/site-packages/eventlet/support/greendns.py", line 623, in _net_read
    s = s + n
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by temoto** [comment]
Try latest version.

Show hostname and type from here

```
  File "/app/phishcheck/phishchecker/views.py", line 385, in check
    ip = socket.gethostbyname(hostname)
```

**Comment by dhhagan** [comment]
@temoto By latest, do you mean 0.23? Or the feature branch? I had the same issue and updated to 0.23 and now get a bytearray issue. I will wait to hear back before opening a new issue (in case I was supposed to use an unreleased version to patch)

**Comment by temoto** [comment]
@dhhagan please show bytearray traceback and minimal code to reproduce it.

**Comment by temoto** [comment]
@dhhagan by latest version most times I refer to last commit in master.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`
