### ISSUE TITLE
Eventlet 0.22  installs dependency enum34 on python 3.6

### ISSUE THREAD

**Issue by ldaverio** [eventlet/eventlet#463]
Hello,

on my machine (OS X 10.13.2, Python 3.6.4 installed from MacPorts, virtualenv), eventlet 0.22.0 incorrectly installs enum34. I suppose the version of Python is not detected correctly:

```
(pydev) $ python --version
Python 3.6.4
(pydev) $ pip install -U eventlet
Collecting eventlet
  Using cached eventlet-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from eventlet)
  Using cached enum34-1.1.6-py3-none-any.whl
Requirement already up-to-date: greenlet>=0.3 in ./pydev/lib/python3.6/site-packages (from eventlet)
Installing collected packages: enum34, eventlet
  Found existing installation: eventlet 0.21.0
    Uninstalling eventlet-0.21.0:
      Successfully uninstalled eventlet-0.21.0
Successfully installed enum34-1.1.6 eventlet-0.22.0
```

Thanks, 

Laurent.

**Comment by temoto** [comment]
@ldaverio please post `venv/bin/pip freeze`

**Comment by temoto** [comment]
@ldaverio scratch that, I have found that packages of interest don't show in `pip freeze`.

Here's proper command: `venv/bin/pip show pip setuptools`

And try this to fix issue:

```shell
venv/bin/pip uninstall -y eventlet enum34
venv/bin/pip install -U pip setuptools
venv/bin/pip install eventlet
```

**Comment by ldaverio** [comment]
Hello,

I created a brand new virtualenv to be sure:

```
$ python3.6 -m venv venv
$ cd venv/
$ . bin/activate
```
Let's check what is outdated:

```
(venv) $ pip list -o
DEPRECATION: The default format will switch to columns in the future. [...]
setuptools (28.8.0) - Latest: 38.4.0 [wheel]
```
So, we update setuptools to the latest version:

```
(venv) $ pip install -U setuptools
Collecting setuptools
  Using cached setuptools-38.4.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed setuptools-38.4.0
```
Now, we have the latest versions of pip and setuptools:

```
(venv) $ pip show pip setuptools
Name: pip
Version: 9.0.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: python-virtualenv@groups.google.com
License: MIT
Location: /Users/daverio/venv/lib/python3.6/site-packages
Requires: 
---
Name: setuptools
Version: 38.4.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /Users/daverio/venv/lib/python3.6/site-packages
Requires: 

```

At that stage, we are ready to install eventlet:

```
(venv) $ pip install eventlet
Collecting eventlet
  Using cached eventlet-0.22.0-py2.py3-none-any.whl
Collecting enum34 (from eventlet)
  Using cached enum34-1.1.6-py3-none-any.whl
Collecting greenlet>=0.3 (from eventlet)
  Using cached greenlet-0.4.12.tar.gz
Installing collected packages: enum34, greenlet, eventlet
  Running setup.py install for greenlet ... done
Successfully installed enum34-1.1.6 eventlet-0.22.0 greenlet-0.4.12
```

enum34 is incorrectly installed as a dependency:

```
(venv) $ pip freeze
enum34==1.1.6
eventlet==0.22.0
greenlet==0.4.12
```

**Comment by ldaverio** [comment]
PS: I was able to reproduce the problem on a FreeBSD 11.1-RELEASE box, using Python 3.6.4 from ports.

**Comment by temoto** [comment]
@ldaverio first, it's still may be my mistake. To exclude it, please execute test 2 in following code.

If I generated proper wheel (that is using latest setuptools), then I'm sorry. I only found solution with updating pip/setuptools on web. And it should have only required update of pip on your end.

Please try these tests (organized for copy-paste):

```
mkdir /tmp/eventlet-enum34-debug
cd /tmp/eventlet-enum34-debug

python3.6 -m venv bootstrap-virtualenv
bootstrap-virtualenv/bin/pip install virtualenv
bootstrap-virtualenv/bin/virtualenv --python=python3.6 venv1
bootstrap-virtualenv/bin/virtualenv --python=python3.6 venv2
bootstrap-virtualenv/bin/virtualenv --python=python3.6 venv3

echo 'test 1'
venv1/bin/pip install -U pip
venv1/bin/pip install eventlet 2>&1 |fgrep enum34

echo 'test 2'
curl -L -o eventlet.zip 'https://github.com/eventlet/eventlet/archive/master.zip'
unzip eventlet.zip
venv2/bin/pip install -U setuptools wheel
venv2/bin/python eventlet-master/setup.py bdist_wheel
venv3/bin/pip install -U pip
venv3/bin/pip install dist/eventlet-0.22.0-py3-none-any.whl 2>&1 |fgrep enum34

cd
rm -rf /tmp/eventlet-enum34-debug
```

If all fails, please try to file this issue against FreeBSD Python port. Problem: not following PEP-508 https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by ulope** [comment]
I'm seeing the same. 

What's even worse: `enum34` doesn't support `IntFlag` which leads to the `re` module no longer being importable (only if `PYTHONPATH` points to the site-packages where enum34 is installed though).

Steps to reproduce:

```
docker run --rm -it python:3.6 /bin/bash
root@920f706d3422:/# python --version
Python 3.6.4
root@920f706d3422:/# python -m venv test-venv
root@920f706d3422:/# . test-venv/bin/activate
(test-venv) root@920f706d3422:/# pip install -U pip setuptools
Requirement already up-to-date: pip in /test-venv/lib/python3.6/site-packages
Collecting setuptools
  Downloading setuptools-38.4.0-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 2.1MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
Successfully installed setuptools-38.4.0
```

```
(test-venv) root@920f706d3422:/# pip install eventlet
Collecting eventlet
  Downloading eventlet-0.22.0-py2.py3-none-any.whl (409kB)
    100% |████████████████████████████████| 409kB 2.6MB/s
Collecting greenlet>=0.3 (from eventlet)
  Downloading greenlet-0.4.12-cp36-cp36m-manylinux1_x86_64.whl (42kB)
    100% |████████████████████████████████| 51kB 7.0MB/s
Collecting enum34 (from eventlet)
  Downloading enum34-1.1.6-py3-none-any.whl
Installing collected packages: greenlet, enum34, eventlet
Successfully installed enum34-1.1.6 eventlet-0.22.0 greenlet-0.4.12
```

```
(test-venv) root@920f706d3422:/# PYTHONPATH=test-venv/lib/python3.6/site-packages/ python
Python 3.6.4 (default, Dec 21 2017, 01:35:12)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
>>>
```

**Comment by temoto** [comment]
Oh this will also work `venv/bin/pip uninstall enum34`
We're so happy that pip doesn't enforce dependency presence unlike many other package managers.

**Comment by ulope** [comment]
Doesn't help when the situation with the `re` module I described above occurs since pip itself imports `re`

**Comment by temoto** [comment]
`PYTHONPATH=venv/lib/python3.6/site-packages venv/bin/pip uninstall -y enum34`

**Comment by temoto** [comment]
@ldaverio please try this. I've recreated package in new virtualenv, supposedly same as worked in venv3.

`pip install -U --index-url https://test.pypi.org/simple/ eventlet`

**Comment by ldaverio** [comment]
@temoto seems to be working for me, on both platforms (FreeBSD and macOS). Well done! :)

(NB: `greenlet` needs to be installed beforehand, but this is probably normal)

**Comment by temoto** [comment]
Fix was released on PyPI as 0.22.1

@ldaverio please try updating from regular pip, without index-url.

**Comment by ldaverio** [comment]
@temoto done, works for me! :)

**Comment by temoto** [comment]
Thank you very much for testing.
