### ISSUE TITLE
OpenSSL handshake failure

### ISSUE THREAD

**Issue by raybotha** [eventlet/eventlet#476]
Attempting to use the Google PubSub client in a greenthread or tpool produces the following error: https://gist.github.com/raybotha/f5de2f07386f0ca845a6d6d201b070c8

Here's example code to reproduce the issue: https://gist.github.com/raybotha/c7f193fce0a2c06418f03defe4a33687

**Comment by temoto** [comment]
Please post `uname -a ; python -V`

**Comment by raybotha** [comment]
Here you go:
`Linux hp 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`Python 3.6.3`

I've tried several different versions of eventlet and Ubuntu.

**Comment by raybotha** [comment]
Without PyOpenSSL installed this is the same, slightly more verbose error I get:
`ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fda34534be0>" raised exception!
Traceback (most recent call last):
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/eventlet/green/ssl.py", line 402, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/eventlet/green/ssl.py", line 91, in __init__
    self.do_handshake()
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/eventlet/green/ssl.py", line 270, in do_handshake
    super(GreenSSLSocket, self).do_handshake)
  File "/home/ray/.virtualenvs/exchange-streaming/lib/python3.6/site-packages/eventlet/green/ssl.py", line 113, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:777)
`

`cachetools==2.0.1
certifi==2018.1.18
chardet==3.0.4
eventlet==0.22.1
google-api-core==1.1.0
google-auth==1.4.1
google-cloud-pubsub==0.32.1
googleapis-common-protos==1.5.3
greenlet==0.4.13
grpc-google-iam-v1==0.11.4
grpcio==1.10.0
idna==2.6
protobuf==3.5.2
psutil==5.4.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pytz==2018.3
requests==2.18.4
rsa==3.4.2
six==1.11.0
urllib3==1.22
`

**Comment by temoto** [comment]
@raybotha If gRPC is compatible with vanilla Python without other libraries, then it must work with eventlet. Otherwise it's a bug in eventlet.

Please, try this patch.

pip install https://github.com/eventlet/eventlet/archive/5739f73ce8c9af9cab128dc1258f2c6b1ee56cbb.zip

**Comment by raybotha** [comment]
@temoto Thanks, the patch doesn't change behaviour though. gRPC recently added support for gevent in a rather large PR (https://github.com/grpc/grpc/pull/14561), which makes me think there is some incompatibility with eventlet as well.

**Comment by raybotha** [comment]
@temoto  You can try my example code above, the error happend before authentication can be done so you won't need valid Google Cloud details.

**Comment by temoto** [comment]
Yes, I'm sorry for fast unsupported claims. I thought gRPC is pure Python stuff and should just work. Did not know that it is Cython based, which makes it basically C extension, which is another story for eventlet and reason why gevent had to make big patch for compatibility.

**Comment by temoto** [comment]
Please try `eventlet.monkey_patch(thread=False)`
it definitely helps, but may introduce blocking problems (like threading lock blocking all greenthreads instead of caller).
