### ISSUE TITLE
Windows: monkey_patch(os=True, subprocess=True) makes check_output() fail

### ISSUE THREAD

**Issue by nat-goodspeed** [eventlet/eventlet#483]
If I simply call `monkey_patch(subprocess=True)`, `subprocess.check_output()` works as expected:

    $ python
    Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import eventlet
    >>> eventlet.__version__
    '0.22.1'
    >>> eventlet.monkey_patch(subprocess=True)
    >>> import subprocess
    >>> print subprocess.check_output(['echo', 'hi'])
    hi

    >>> exit()

However, if I *also* pass `os=True`, `subprocess.check_output()` fails, apparently because it's trying to use a Windows anonymous pipe instead of a named pipe:

    $ python
    Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import eventlet
    >>> eventlet.__version__
    '0.22.1'
    >>> eventlet.monkey_patch(os=True, subprocess=True)
    >>> import subprocess
    >>> print subprocess.check_output(['echo', 'hi'])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "c:\python27\Lib\subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "c:\python27\Lib\subprocess.py", line 420, in __init__
        self.stdout = os.fdopen(c2pread, 'rb', bufsize)
      File "C:\Users\Nat\virtualenvs\eventlet-clean\lib\site-packages\eventlet\green\os.py", line 28, in fdopen
        return greenio.GreenPipe(fd, *args, **kw)
      File "C:\Users\Nat\virtualenvs\eventlet-clean\lib\site-packages\eventlet\greenio\py2.py", line 42, in __init__
        set_nonblocking(self)
      File "C:\Users\Nat\virtualenvs\eventlet-clean\lib\site-packages\eventlet\greenio\base.py", line 99, in set_nonblocking
        raise NotImplementedError("set_nonblocking() on a file object "
    NotImplementedError: set_nonblocking() on a file object with no setblocking() method (Windows pipes don't support non-blocking I/O)
    >>> exit()

**Comment by temoto** [comment]
Thanks.

**Comment by temoto** [comment]
On windows a local socket would probably work for subprocess synchronization.

**Comment by nat-goodspeed** [comment]
That's true; but for nonblocking I/O to a Windows child process, use of a named pipe with a generated name is more typical.

**Comment by nat-goodspeed** [comment]
I encountered a different odd interaction of `monkey_patch()` options on macOS 10.12.6: if you pass `builtins=True` and `subprocess=True`, you *must* also pass `os=True`.

With only `builtins=True` and `subprocess=True`:

    $ python
    Python 2.7.14 (default, Sep 22 2017, 00:06:07) 
    [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import eventlet
    >>> eventlet.__version__
    '0.22.1'
    >>> eventlet.monkey_patch(builtins=True, subprocess=True)
    >>> import subprocess
    >>> print subprocess.check_output(['echo', 'hi'])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/Users/nat/virtualenvs/eventlet-clean/lib/python2.7/site-packages/eventlet/green/subprocess.py", line 75, in __init__
        wrapped_pipe = greenio.GreenPipe(pipe, mode, bufsize)
      File "/Users/nat/virtualenvs/eventlet-clean/lib/python2.7/site-packages/eventlet/greenio/py2.py", line 25, in __init__
        raise TypeError('f(ile) should be int, str, unicode or file, not %r' % f)
    TypeError: f(ile) should be int, str, unicode or file, not <open file '<fdopen>', mode 'rb' at 0x106f14ed0>
    >>> exit()

Adding `os=True`:

    $ python
    Python 2.7.14 (default, Sep 22 2017, 00:06:07) 
    [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import eventlet
    >>> eventlet.__version__
    '0.22.1'
    >>> eventlet.monkey_patch(os=True, builtins=True, subprocess=True)
    >>> import subprocess
    >>> print subprocess.check_output(['echo', 'hi'])
    hi

    >>> exit()
 
Since the code I'm using wants to pass both `builtins=True` and `subprocess=True`, evidently I must pass `os=(platform.system() != 'Windows')`.

**Comment by dantingl** [comment]
Hi,
Any update on this issue? I hit this error too when using monkey_patch() on Windows.

**Comment by cyborgx0x** [comment]
I got the same issue when open file:
```
self.converted_file.save(f"{file_name}.docx", File(open(converted, "rb")))
```
