### ISSUE TITLE
import eventlet breaks dns lookups using tcp

### ISSUE THREAD

**Issue by rgbyrnes** [eventlet/eventlet#499]
Here's a simple reproducer.  It works if we don't import eventlet, or if we omit tcp=True.

```
Python 2.7.15 (default, May  9 2018, 14:07:52)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.version
>>> dns.version.version
'1.15.0'
>>> from dns.resolver import query
>>> import eventlet
>>> eventlet.__version__
'0.23.0'
>>> query('github.com', 'a', tcp=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/dns/resolver.py", line 957, in query
    source_port=source_port)
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/eventlet/support/greendns.py", line 803, in tcp
    r = dns.message.from_wire(wire, keyring=q.keyring, request_mac=q.mac)
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/dns/message.py", line 806, in from_wire
    ignore_trailing)
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/dns/message.py", line 599, in __init__
    self.wire = dns.wiredata.maybe_wrap(wire)
  File "/usr/local/python/python-2.7/std/lib/python2.7/site-packages/dns/wiredata.py", line 103, in maybe_wrap
    raise ValueError("unhandled type %s" % type(wire))
ValueError: unhandled type <type 'bytearray'>
```

**Comment by temoto** [comment]
@rgbyrnes please, try latest master with patch from @beltran 

`pip install https://github.com/eventlet/eventlet/archive/master.zip`
