### ISSUE TITLE
ImportError: No module named dnskeybase

### ISSUE THREAD

**Issue by macdonjo** [eventlet/eventlet#556]
Any idea why `ImportError: No module named dnskeybase` would raise when importing eventlet?

**Comment by kashirin-alex** [comment]
it is https://github.com/eventlet/eventlet/blob/master/eventlet/support/greendns.py#L67

what python version do you use?

What are the outputs for : 
 1) import dns.rdtypes.dnskeybase 
 2) from dns.rdtypes import dnskeybase 
 3) import dns
     dns.rdtypes.dnskeybase

**Comment by jstasiak** [comment]
Yes, the error alone is far from sufficient. At least the Python version, Eventlet version and full stack trace are needed to try to diagnose this.

**Comment by macdonjo** [comment]
Python 2.7.5
Eventlet 0.24.1

Trace:
```
Traceback (most recent call last):
  File "project.py", line 3, in <module>
    import threading, eventlet
  File "/usr/lib/python2.7/site-packages/eventlet/__init__.py", line 10, in <module>
    from eventlet import convenience
  File "/usr/lib/python2.7/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/lib/python2.7/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/usr/lib/python2.7/site-packages/eventlet/support/greendns.py", line 67, in <module>
    setattr(dns.rdtypes, pkg, import_patched('dns.rdtypes.' + pkg))
  File "/usr/lib/python2.7/site-packages/eventlet/support/greendns.py", line 59, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/usr/lib/python2.7/site-packages/eventlet/patcher.py", line 120, in import_patched
    *additional_modules + tuple(kw_additional_modules.items()))
  File "/usr/lib/python2.7/site-packages/eventlet/patcher.py", line 94, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
ImportError: No module named dnskeybase

```

**Comment by kashirin-alex** [comment]
You must check on your dnspython installation.
eg. pip install --upgrade dnspython

output on my side it is:
```
Python 2.7.15 (default, Dec 19 2018, 04:39:24)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.rdtypes.dnskeybase
>>> from dns.rdtypes import dnskeybase
>>> import dns
>>> dns.rdtypes.dnskeybase
<module 'dns.rdtypes.dnskeybase' from '/usr/local/lib/python2.7/site-packages/dns/rdtypes/dnskeybase.pyc'>
>>>

```

**Comment by macdonjo** [comment]
@kashirin-alex 

`# pip install --upgrade dnspython
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: dnspython in /usr/lib/python2.7/site-packages (1.16.0)`

**Comment by macdonjo** [comment]
I gave up with this issue and upgraded to Python 3.6

**Comment by hnyztang** [comment]
i just get problem , would told me how to fix it?

**Comment by macdonjo** [comment]
Not possible. There is no fix.

**Comment by hnyztang** [comment]
> Not possible. There is no fix.
the demo comes from :https://python-socketio.readthedocs.io/en/latest/intro.html#server-examples
i use  pyinstaller -F   xxxxx.py     , but running failed.
