### ISSUE TITLE
_green_existing_locks raises an attribute error under PyPy2.7 v 7.x.x

### ISSUE THREAD

**Issue by olliemath** [eventlet/eventlet#559]
## Issue

Calling `monkey_patch` on PyPy 2.7 v7.x.x causes an AttributeError if there are any existing RLock objects.
```python
Python 2.7.13 (...)
[PyPy 7.1.0 with GCC 8.2.1 20181127] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from threading import RLock
>>>> import eventlet
>>>> lock = RLock()
>>>> lock.acquire()
True
>>>> eventlet.monkey_patch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oliver/.virtualenvs/enventletpypy/site-packages/eventlet/patcher.py", line 265, in monkey_patch
    _green_existing_locks()
  File "/home/oliver/.virtualenvs/enventletpypy/site-packages/eventlet/patcher.py", line 358, in _green_existing_locks
    isinstance(obj._RLock__block, lock_type)):
AttributeError: 'thread.RLock' object has no attribute '_RLock__block'
```

Here's a minimal dockerfile if you want to reproduce locally:
```docker
FROM pypy:2-7.0.0
RUN pip install eventlet==0.24.1

RUN echo "from threading import RLock; import eventlet; lock = RLock(); lock.acquire(); eventlet.monkey_patch()" > /run.py
ENTRYPOINT ["pypy", "/run.py"]
```

## Cause

The latest version of PyPy backports `threading._CRLock` from Python3. It uses this as `threading.RLock` and demotes the original python implementation to `threading._PyRLock`.

**Comment by gordol** [comment]
seems like this should be simple to patch here?
https://github.com/eventlet/eventlet/blob/master/eventlet/patcher.py#L318

**Comment by gordol** [comment]
gevent fix over here for reference: https://github.com/gevent/gevent/pull/1357

**Comment by gordol** [comment]
and there's a PR already over here: https://github.com/eventlet/eventlet/pull/547
