### ISSUE TITLE
Prevent backdoor from being shutdown by the client

### ISSUE THREAD

**Issue by xqliang** [eventlet/eventlet#570]
I have a service process that started the backdoor, once i accidentally execute `echo close | telnet localhost <port>`, and the backdoor exited.

```bash
$ lsof -nPp 16365 | grep LISTEN
python 16365 xqliang    6u  IPv4 2110325292       0t0        TCP 127.0.0.1:40755 (LISTEN)
python 16365 xqliang   19u  IPv4 2110325310       0t0        TCP *:18601 (LISTEN)

$ echo close | telnet localhost 40755
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

$ lsof -nPp 16365|grep LISTEN
python 16365 xqliang   19u  IPv4 2110325310       0t0        TCP *:18601 (LISTEN)
```

I add a `raise` line at [eventlet/backdoor.py#L107](https://github.com/eventlet/eventlet/blob/master/eventlet/backdoor.py#L107):

```python
    try:
        try:
            while True:
                socketpair = sock.accept()
                backdoor(socketpair, locals)
        except socket.error as e:
            raise         # XXX: Add this line
            # Broken pipe means it was shutdown
            if get_errno(e) != errno.EPIPE:
                raise
    finally:
        sock.close()
```

And got the following traceback:

```
Traceback (most recent call last):
  File "local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
  File "local/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "local/lib/python2.7/site-packages/eventlet/backdoor.py", line 66, in switch
    greenlets.greenlet.switch(self, *args, **kw)
  File "local/lib/python2.7/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "local/lib/python2.7/site-packages/eventlet/backdoor.py", line 104, in backdoor_server
    socketpair = sock.accept()
  File "local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 220, in accept
    timeout_exc=socket.timeout("timed out"))
  File "local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
  File "local/lib/python2.7/site-packages/eventlet/backdoor.py", line 58, in run
    console.interact()
  File "/usr/lib/python2.7/code.py", line 234, in interact
    line = self.raw_input(prompt)
  File "/usr/lib/python2.7/code.py", line 281, in raw_input
    return raw_input(prompt)
  File "local/lib/python2.7/site-packages/eventlet/backdoor.py", line 36, in write
    self.f.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 390, in sendall
    tail = self.send(data, flags)
  File "local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 384, in send
    return self._send_loop(self.fd.send, data, flags)
  File "local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 371, in _send_loop
    return send_method(data, *args)
error: [Errno 32] Broken pipe
```

Can you ignore exceptions caused by the client without exit the backdoor?

**Comment by tipabu** [comment]
Huh... that seemed to be the _intent_ of the `except socket.error` block, but I think the loop is misplaced. Mind trying something like

    try:
        while True:
            socketpair = None
            try:
                socketpair = sock.accept()
                backdoor(socketpair, locals)
            except socket.error as e:
                # Broken pipe means it was shutdown
                if get_errno(e) != errno.EPIPE:
                    raise
            finally:
                if socketpair:
                    socketpair[0].close()
    finally:
        sock.close()

?

(Side note: I never knew we had this feature! Interesting...)

**Comment by xqliang** [comment]
> Huh... that seemed to be the _intent_ of the `except socket.error` block, but I think the loop is misplaced. Mind trying something like
> 
> ```
> try:
>     while True:
>         socketpair = None
>         try:
>             socketpair = sock.accept()
>             backdoor(socketpair, locals)
>         except socket.error as e:
>             # Broken pipe means it was shutdown
>             if get_errno(e) != errno.EPIPE:
>                 raise
>         finally:
>             if socketpair:
>                 socketpair[0].close()
> finally:
>     sock.close()
> ```
> 
> ?
> 
> (Side note: I never knew we had this feature! Interesting...)

It works :)
