### ISSUE TITLE
[Windows] Only first dns server on the list queried

### ISSUE THREAD

**Issue by jacekchalupka** [eventlet/eventlet#596]
With eventlet-0.25.1

```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import socket
>>> socket.getaddrinfo('google.com', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\virtualenvs\dev\lib\site-packages\eventlet\support\greendns.py", line 537, in getaddrinfo
    raise socket.gaierror(socket.EAI_NONAME, 'No address found')
socket.gaierror: [Errno 11001] No address found
```

Without monkey_patching:
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('google.com', 0)
[(<AddressFamily.AF_INET: 2>, 0, 0, '', ('172.217.164.110', 0))]
```

It is not https://github.com/eventlet/eventlet/issues/589, because:
```
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import dns.resolver
>>> dns.resolver.Resolver().nameservers
['10.5.88.20', '10.5.88.23', '8.8.8.8', '8.8.4.4', '10.1.0.20']
```

After catching packets with Wireshark I noticed that after monkey_patching only first DNS server on the list is queried and on my setup it is not responding right now.

**Comment by zhangyangyu** [comment]
The green dns.getaddrinfo uses dnspython. According to https://github.com/rthalley/dnspython/pull/367 the behavior is expected.
