### ISSUE TITLE
getaddrinfo doesn't support host parameter of type bytes

### ISSUE THREAD

**Issue by Akrog** [eventlet/eventlet#599]
Python's getaddrinfo supports bytes as the host parameter, but greendns's getaddrinfo doesn't and fails with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eventlet/support/greendns.py", line 517, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "eventlet/support/greendns.py", line 479, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "eventlet/support/greendns.py", line 425, in resolve
    use_network=use_network)
  File "eventlet/support/greendns.py", line 380, in query
    return end()
  File "eventlet/support/greendns.py", line 359, in end
    raise result[1]
  File "eventlet/support/greendns.py", line 340, in step
    a = fun(*args, **kwargs)
  File "dns/resolver.py", line 858, in query
    if qname.is_absolute():
AttributeError: 'bytes' object has no attribute 'is_absolute'
```

**Comment by ShaneHarvey** [comment]
I also encountered this issue in https://jira.mongodb.org/browse/PYTHON-3451. My fix was to avoid passing bytes to getaddrinfo but it would be great for eventlet to become consistent with the stdlib and allow bytes.
