### ISSUE TITLE
ModuleNotFoundError: No module named 'eventlet.hubs.epolls' 

### ISSUE THREAD

**Issue by hnyztang** [eventlet/eventlet#605]
Mac OS , how to fix it .  i have no idea.  the program is packed by pyinstaller.  
if running  "python Transerfer.py"  in iTerms  is ok. 

Traceback (most recent call last):
  File "TransferClient.py", line 1, in <module>
    import eventlet
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/__init__.py", line 10, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/convenience.py", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/greenpool.py", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/queue.py", line 49, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/event.py", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/eventlet/hubs/__init__.py", line 19, in <module>
  File "site-packages/eventlet/hubs/__init__.py", line 19, in <genexpr>
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'eventlet.hubs.epolls'
[4671] Failed to execute script TransferClient

**Comment by temoto** [comment]
So the problem is it tries to use epoll system event dispatch mechanism which is only present on Linux.

For OSX appropriate hub is kqueue. You can enforce it with environment variable `EVENTLET_HUB=kqueue`

Proper hub should be selected automatically. I've never used pyinstaller or anything else packing Python, so have no idea what exactly goes wrong there. You may wish to report issue to pyinstaller and maybe they will suggest a better solution.
