### ISSUE TITLE
GreenSocket conflict with pysocks

### ISSUE THREAD

**Issue by terryzhu** [eventlet/eventlet#616]
Combine `eventlet` and `pysocks`, it will cause `RecursionError: maximum recursion depth exceeded
`

## Code example
```
import eventlet
eventlet.monkey_patch()

import socket
import socks

def test_block_connect():
    s = socks.socksocket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('example.com', 80))

gt = eventlet.spawn(test_block_connect)
gt.wait()
```
### Actual behaviour
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 461, in fire_timers
    timer()
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/usr/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "eventlet_sample.py", line 10, in test_block_connect
    s.connect(('example.com', 80))
  File "/usr/lib/python3.6/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/socks.py", line 774, in connect
    super(socksocket, self).settimeout(self._timeout)
  File "/usr/lib/python3.6/site-packages/eventlet/greenio/base.py", line 418, in settimeout
    self.setblocking(True)
  File "/usr/lib/python3.6/site-packages/socks.py", line 296, in setblocking
    self.settimeout(None)
  File "/usr/lib/python3.6/site-packages/socks.py", line 287, in settimeout
    super(socksocket, self).settimeout(self._timeout)
.....
.....
.....
.....
  File "/usr/lib/python3.6/site-packages/eventlet/greenio/base.py", line 418, in settimeout
    self.setblocking(True)
  File "/usr/lib/python3.6/site-packages/socks.py", line 296, in setblocking
    self.settimeout(None)
RecursionError: maximum recursion depth exceeded
```
### Root cause
[GreenSocket settimeout](https://github.com/eventlet/eventlet/blob/336773da5666cfaec4bd8ca167b5cd40073214a5/eventlet/greenio/base.py#L415) will call setblocking, it will call pysocks [setblocking](https://github.com/Anorov/PySocks/blob/c2fa43cbe1091e799e248e8e4433978916791a8b/socks.py#L294), it will call **GrenSocket settimeout** again, infinitely.

**Comment by leoch20** [comment]
Same here

**Comment by greenfrogs** [comment]
I am having the same problem with gunicorn, has anyone found a workaround?

**Comment by terryzhu** [comment]
> I am having the same problem with gunicorn, has anyone found a workaround?

If you can modify the source code after you install  `pysocks`, maybe you could add the following logic:
original code:
```
def setblocking(self, v):
    if v:
        self.settimeout(None)
    else:
        self.settimeout(0.0)
```
Modified to:
```
def setblocking(self, v):
    if self._timeout == v:
        return
    if v:
        self.settimeout(None)
    else:
        self.settimeout(0.0)
```
To break the recursive method invoking

**Comment by temoto** [comment]
@terryzhu sorry. Usually we have a policy "if it works in vanilla Python then it's a bug in Eventlet". In this case IMHO they (ab)used `setblocking/settimeout` API in wrong way.

If someone comes up with a patch that could fix this on eventlet side, I'd be happy to know, please reopen. But so far it doesn't seem possible to me. Sorry.

As workaround, you may use older version of pysocks.

**Comment by temoto** [comment]
Watch this issue https://github.com/Anorov/PySocks/issues/121
