### ISSUE TITLE
ssl handshake failure stack traces

### ISSUE THREAD

**Issue by delli007** [eventlet/eventlet#620]
The issue here is having an unhandled ssl.SSLError which prints a stack trace to the console. This happens when making a standard http request to the server when wrap_ssl is used, or restarting the server and having an existing socketio https connection. The server continues to run just fine but it seems like these errors should be handled and we should have an option to suppress the error and stack trace.

**Environment:** 
Python 3.6 on CentOS 7, updated to date, and all packages are the latest install using pip3 v20.1.1.
I'm using flask socketio and passing SSL certs and other options which get processed by eventlet.wrap_ssl() and eventlet.wsgi.server()

Tried running eventlet.monkey_patch() and passing the following options but the trace still occurs.
eventlet_options = {'certfile': certfile, 'keyfile': keyfile, 
                'suppress_ragged_eofs': True, 
                'do_handshake_on_connect': False,
                }

**Traces:**
```
10.0.2.2 - - [25/Jun/2020 12:58:53] "POST /socket.io/?EIO=3&transport=polling&t=NBiQiC9&sid=50e79a8c865c489ab8461bd8c0f8be35 HTTP/1.1" 200 220 0.009995

(15075) accepted ('10.0.2.2', 1047)
10.0.2.2 - - [25/Jun/2020 12:58:53] "GET /socket.io/?EIO=3&transport=polling&t=NBiQiCP&sid=50e79a8c865c489ab8461bd8c0f8be35 HTTP/1.1" 200 304 0.000762
Traceback (most recent call last):
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 150, in _call_trampolining      
    return func(*a, **kw)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2334)
Removing descriptor: 10
(15075) accepted ('10.0.2.2', 1048)

10.0.2.2 - - [25/Jun/2020 13:25:17] "GET /socket.io/?EIO=3&transport=polling&t=NBiWk32&sid=7b71cee87b4d479798f5c7cef92a3def HTTP/1.1" 200 391 0.000748
(15143) accepted ('10.0.2.2', 31123)
Traceback (most recent call last):
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 150, in _call_trampolining      
    return func(*a, **kw)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2334)
Removing descriptor: 15
10.0.2.2 - - [25/Jun/2020 13:25:17] "GET /socket.io/?EIO=3&transport=polling&t=NBiWk3R&sid=7b71cee87b4d479798f5c7cef92a3def HTTP/1.1" 200 183 0.000699
10.0.2.2 - - [25/Jun/2020 13:25:19] "GET /socket.io/?EIO=3&transport=polling&t=NBiWkmn HTTP/1.1" 200 349 0.000460
(15143) accepted ('10.0.2.2', 31125)
[2020-06-25 13:25:19,945] [GreenThread-] [INFO ]  admin connected to namespace /api
10.0.2.2 - - [25/Jun/2020 13:25:19] "POST /socket.io/?EIO=3&transport=polling&t=NBiWkmz&sid=57093e8bc5224d97b7e0eaa0f01147a8 HTTP/1.1" 200 220 0.006155
10.0.2.2 - - [25/Jun/2020 13:25:19] "GET /socket.io/?EIO=3&transport=polling&t=NBiWkn2&sid=57093e8bc5224d97b7e0eaa0f01147a8 HTTP/1.1" 200 304 0.000501
Traceback (most recent call last):
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/opt/neo-env/lib64/python3.6/site-packages/eventlet/green/ssl.py", line 150, in _call_trampolining      
    return func(*a, **kw)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:2334)
Removing descriptor: 15
```

**Comment by temoto** [comment]
Yes, we could adopt nginx `497 HTTP Request Sent to HTTPS Port`

Patch is warmly welcome.

**Comment by Achelics** [comment]
who can resolve the problem? I also met this question, I use the self-signed certificate
