### ISSUE TITLE
Monkey patching breaks usage of subprocess.TimeoutExpired

### ISSUE THREAD

**Issue by dtantsur** [eventlet/eventlet#624]
Reproducer (on Python 3.8 for me, also seems to reproduce on 3.6):

```python
import eventlet
eventlet.monkey_patch()

import subprocess


try:
    subprocess.check_call('sleep 10', shell=True, timeout=1)
except subprocess.TimeoutExpired:
    print('okay')
except Exception as exc:
    assert exc.__class__ is subprocess.TimeoutExpired, exc.__class__
```

Expected: "okay" printed.
Actual:
```
Traceback (most recent call last):
  File "../_timeout.py", line 8, in <module>
    subprocess.check_call('sleep 10', shell=True, timeout=1)
  File "/usr/lib64/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/home/dtantsur/Projects/oslo.concurrency/.tox/py3/lib/python3.8/site-packages/eventlet/green/subprocess.py", line 90, in wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command 'sleep 10' timed out after 1 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../_timeout.py", line 12, in <module>
    assert exc.__class__ is subprocess.TimeoutExpired, exc.__class__
AssertionError: <class 'subprocess.TimeoutExpired'>
```

Using
```python
from eventlet.green import subprocess
```
fixes the problem but assumes modifying the code which is supposed to work after monkey patching.

**Comment by dtantsur** [comment]
This issue seems highly dependant on versions, presence of virtual env and moon phases. I do wonder if we should avoid overriding `TimeoutExpired` for Python's that have it.

**Comment by temoto** [comment]
Maybe related to this branch https://github.com/eventlet/eventlet/commits/subprocess-413-more https://github.com/eventlet/eventlet/commit/18c889e99360ddf76cdcad42090fd87e481e84fb though it doesn't apply to `TimeoutExpired` and maybe should.
