### ISSUE TITLE
CPython 2 deprecated support warning by cryptography breaks output checking tests

### ISSUE THREAD

**Issue by temoto** [eventlet/eventlet#636]
Example:
```
FAIL: test_simple (tests.patcher_test.Tpool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/eventlet/eventlet/tests/__init__.py", line 78, in wrapped
    return func(*a, **kw)
  File "/home/travis/build/eventlet/eventlet/tests/patcher_test.py", line 249, in test_simple
    self.assertEqual(len(lines), 3, output)
AssertionError: /home/travis/build/eventlet/eventlet/.tox/py27-epolls/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
newmod 2
newmod 3
```

Solution: ignore CryptographyDeprecationWarning or warnings with "Python 2 is no longer supported" substring.

**Comment by temoto** [comment]
Fixed in master by 3a01b33250a6b0504d506b79e563e7445b0ecc77
