### ISSUE TITLE
Example from README.me doesn't work: No module named 'urllib2'

### ISSUE THREAD

**Issue by vitlav** [eventlet/eventlet#668]
```
$ pip install eventlet
...
Successfully installed dnspython-1.16.0 eventlet-0.29.1 greenlet-0.4.17 six-1.15.0
...
$ python3
Python 3.8.6 (default, Oct  2 2020, 00:06:33) 
...
>>> import eventlet
>>> from eventlet.green import urllib2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.private/lav/7/test/lib/python3/site-packages/eventlet/green/urllib2.py", line 9, in <module>
    patcher.inject(
  File "/tmp/.private/lav/7/test/lib/python3/site-packages/eventlet/patcher.py", line 106, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
ModuleNotFoundError: No module named 'urllib2
```

**Comment by temoto** [comment]
@vitlav thank you. `eventlet.green` package content is API compatible with Python stdlib. That example was written against Python2 stdlib. In Python3 it's called `urllib.request`. I'll update doc since we're going to remove py2 support anyway.

**Comment by temoto** [comment]
@vitlav thanks, fixed in master.
