### ISSUE TITLE
TypeError: changelist must be an iterable of select.kevent objects on Python 3.9/OSX

### ISSUE THREAD

**Issue by pwinston** [eventlet/eventlet#670]
I'm using eventlet 0.29.1 with Flask-SocketIO 4.3.1 and Python 3.9 on MacOS.

I tried added `eventlet.monkey_patch()` hoping to cure my server of hanging on exit.

My program uses `SharedMemoryManager` to connect to a process, kind of on the other side of things away from the SocketIO part. And `monkey_patch()` causes this error when I call `SharedMemoryManager.connect()`:

`TypeError: changelist must be an iterable of select.kevent objects`

    Traceback (most recent call last):
    File "/Users/pbw/dev/webmon/webmon.py", line 225, in <module>
        main()
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
    File "/Users/pbw/dev/webmon/webmon.py", line 211, in main
        client = create_napari_client("webmon")
    File "/Users/pbw/dev/webmon/napari_client.py", line 193, in create_napari_client
        return MonitorClient(config, client_name)
    File "/Users/pbw/dev/webmon/napari_client.py", line 115, in __init__
        self._manager.connect()
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/multiprocessing/managers.py", line 522, in connect
        conn = Client(self._address, authkey=self._authkey)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/multiprocessing/connection.py", line 507, in Client
        c = SocketClient(address)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
        s.connect(address)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/eventlet/greenio/base.py", line 250, in connect
        self._trampoline(fd, write=True)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/eventlet/greenio/base.py", line 208, in _trampoline
        return trampoline(fd, read=read, write=write, timeout=timeout,
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/eventlet/hubs/__init__.py", line 157, in trampoline
        listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 53, in add
        self._control([event], 0, 0)
    File "/Users/pbw/miniconda3/envs/napari39/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 39, in _control
        return self.kqueue.control(events, max_events, timeout)
    TypeError: changelist must be an iterable of select.kevent objects

**Comment by temoto** [comment]
Hey that seems like a somewhat easy buf in kqueue hub.

Please try Python3.7-3.8 if you can.

**Comment by temoto** [comment]
And of course, `EVENTLET_HUB=poll` environment should be a good enough workaround for now. It's unlikely you'd run this under high load on OSX, right?

**Comment by pwinston** [comment]
I can't easily run older Python's right now, due to other dependencies unrelated to eventlet.

Setting `EVENTLET_HUB=poll` does fix the error!

Also just removing `monkey_patch()` fixes it. I thought I needed `monkey_patch()` to fix a hang on exit, but I fixed that another way.

So I can run two ways under Python 3.9:

1.  Without `monkey_patch()`
2. With `monkey_patch()` but use `EVENTLET_HUB=poll`.

I'm totally new to eventlet. We are writing a Flask-SocketIO server that's updating at 60Hz, but should generally have just 1 connected user!

**Comment by temoto** [comment]
@pwinston IMHO Python threads are decent solution for under 100 concurrent connections. Maybe you don't need Eventlet after all.

Still there is a bug in kqueue hub. Could you provide a minimal issue reproduction script?

**Comment by pwinston** [comment]
This reproduces the problem:

    import eventlet

    eventlet.monkey_patch()
    from multiprocessing.managers import BaseManager

    manager = BaseManager(address=('localhost', 5010), authkey=str.encode('XXX'))
    manager.connect()

Yeah probably 1 concurrent connection!

Flask-SocketIO does give the best explanation of the options. It says use eventlet, or gevent, or "The Flask development server based on Werkzeug" but it poo-poohs that option.

https://flask-socketio.readthedocs.io/en/latest/

**Comment by temoto** [comment]
Thanks a lot. So the bug is indeed Python 3.9 specific, this code works on 3.8. Shorter repro script:

```
import eventlet
eventlet.connect(('127.0.0.1', 1234))
```

Flask-SocketIO doc says dev server can't talk websocket, only long polling, which is really unfortunate. Before abandoning websocket option, maybe you should check that all different features of your browser-backend interaction work fine and under degraded network too. I know very little about SocketIO to suggest in which situations websocket transport is clearly superior to long polling.

**Comment by temoto** [comment]
Other kevent platforms like FreeBSD should suffer from this issue, in theory.

**Comment by hecko** [comment]
Im suffering from this as of today 

```
Darwin 192.168.0.100 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

Python 3.9.6 from brew

Requirement already satisfied: eventlet in /usr/local/lib/python3.9/site-packages (0.31.1)

used with
Requirement already satisfied: python-socketio in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (5.3.0)
```

```
marcel@192 ServerPython % ./websocket_listener.py
(20442) wsgi starting up on http://0.0.0.0:8080
(20442) wsgi exited, is_accepting=True
Traceback (most recent call last):
  File "/Users/marcel/git/archive-uploader-capacitor/ServerPython/./websocket_listener.py", line 47, in <module>
    eventlet.wsgi.server(eventlet.listen(("", 8080)), app)
  File "/usr/local/lib/python3.9/site-packages/eventlet/wsgi.py", line 980, in server
    client_socket, client_addr = sock.accept()
  File "/usr/local/lib/python3.9/site-packages/eventlet/greenio/base.py", line 230, in accept
    self._trampoline(fd, read=True, timeout=self.gettimeout(), timeout_exc=_timeout_exc)
  File "/usr/local/lib/python3.9/site-packages/eventlet/greenio/base.py", line 208, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "/usr/local/lib/python3.9/site-packages/eventlet/hubs/__init__.py", line 155, in trampoline
    listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed)
  File "/usr/local/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 53, in add
    self._control([event], 0, 0)
  File "/usr/local/lib/python3.9/site-packages/eventlet/hubs/kqueue.py", line 39, in _control
    return self.kqueue.control(events, max_events, timeout)
TypeError: changelist must be an iterable of select.kevent objects
```

the workaround with


```

EVENTLET_HUB=poll
```

works

**Comment by luvpreetsingh** [comment]
We are running a django project. We just added eventlet in our requirements and now my django commands are not working.

When I run `python manage.py runserver`, it works but when I stop it using Ctrl-C, it gives this error.
`python manage.py makemigrations` doesn't run at all.

I tried adding `EVENTLET_HUB=poll` env var but that is also not working.

Any help will be appreciated.

**Comment by temoto** [comment]
@luvpreetsingh eventlet is only compatible with Python <= 3.8 right now.

**Comment by luvpreetsingh** [comment]
@temoto Thank you for the quick response.

Any reason why this does not happen on windows?

**Comment by temoto** [comment]
Kqueue event mechanism is not available on Windows.

**Comment by maiux** [comment]
Hello, I stepped into this problem running [changedetection.io](https://github.com/dgtlmoon/changedetection.io) (uses eventlet) in a conda environment on Intel macOS Big Sur with python 3.9.

To investigate I tried to run in vscode Version: 1.59.1 (Universal) with "Start debugging" but _the problem didn't show up_ so I tried to run with "Run without debugging" and got TypeError. 

FYI

**Comment by rajasimon** [comment]
@temoto I get this error in `Python3.9.9` `eventlet==0.33.0`  `changelist must be an iterable of select.kevent objects` 

Do you have any workaround of this? I don't want to switch to another python version because there is lot of dependencies I need to check from my end.

**Comment by temoto** [comment]
# Status

As of 2021-11-30, eventlet 0.33.0 and below doesn't support Python3.9+/kqueue (default hub on FreeBSD, Mac OSX, possibly other BSDs).

# Workaround

Set environment `EVENTLET_HUB=poll` -- Warning. This may drop performance substantially. Do tests.

@rajasimon

**Comment by temoto** [comment]
closed by mistake

**Comment by temoto** [comment]
@rajasimon I hope you undertood traceback and settings really well, because AFAIK, asyncio and eventlet can't possibly work together, they try to control the same thing: process idle time.

**Comment by mforbes** [comment]
I am having a similar issue when using Sphinx to try to generate documentation which imported flask and eventlet.  Dropping back to Python 3.8 fixed the issue, as did mocking the eventlet import while running Sphinx by adding the following to `conf.py`:

```python
# conf.py
autodoc_mock_imports = ["eventlet"]
```

**Comment by BrianMuigai** [comment]
Serving it with Gunicorn might be a good workaround
`gunicorn --worker-class eventlet -w 1 app:app --reload --bind 0.0.0.0:8080 --log-level debug`

**Comment by leetrout** [comment]
This was a head scratcher for me. Thank you for the information. I can also confirm having `eventlet` installed on macos with Python 3.9.10 caused issues with Django.

Uninstalled eventlet and the issue went away. Reinstalled and set the Django unsafe flag unblocked me.

Looking forward to a fix at the source when possible 👍

**Comment by ErikBrendel** [comment]
For others stumbling across the same issue: For me, I was trying to get pytest-playwright to run (which using asyncio under the hood) on python3.9 on a M1 Mac, getting an error message similar to @rajasimon, and simply running `pip uninstall eventlet` solved the issue for me!

**Comment by rememberlenny** [comment]
I was trying to run Flask[async] and uninstalling eventlet was also the solution.

**Comment by cwooldridge1** [comment]
What fixed my issue on python 3.9.7 is importing `select` at the top of the program
```python
import select
import eventlet
eventlet.monkey_patch()

from app import createApp

app = createApp()

if __name__ == '__main__':
    # Use the eventlet WSGI server
    eventlet.wsgi.server(eventlet.listen(('localhost', 8080)), app)
```

**Comment by temoto** [comment]
@cwooldridge1 thanks for sharing that

**Comment by gemlabsdev** [comment]
> What fixed my issue on python 3.9.7 is importing `select` at the top of the program
> 
> ```python
> import select
> import eventlet
> eventlet.monkey_patch()
> 
> from app import createApp
> 
> app = createApp()
> 
> if __name__ == '__main__':
>     # Use the eventlet WSGI server
>     eventlet.wsgi.server(eventlet.listen(('localhost', 8080)), app)
> ```

Thank you very much for sharing! With this there is also no need for ```EVENTLET_HUB=poll```

**Comment by philippkeller** [comment]
I was on `python 3.9` and neither adding select at top nor starting with `EVENTLET_HUB=poll` helped.

But upgrading to python 3.11 solved the issue

**Comment by believetech-orw** [comment]
I was also getting this error trying to run a python script w python 3.9.6.  I already had "EVENTLET_HUB": "poll" in the environment variables of the launch.json configuration.  I ALSO needed to add `"gevent": false` to my launch configuration, at the same level as "env": {}
