### ISSUE TITLE
RuntimeError: Redis requires a monkey patched socket library to work with eventlet

### ISSUE THREAD

**Issue by mischa85** [eventlet/eventlet#678]
This error got introduced in eventlet 0.26.1-2 which is rebuild for Python 3.9.

https://github.com/archlinux/svntogit-community/commit/92643bdd51e1777d9672ad312be63f190921bb99

It is present in the py39 patched 0.29.1-1 and also in the unpatched 0.30.0.

```
Dec 15 01:09:48 knaagbeest gunicorn[712]: connect handler error
Dec 15 01:09:48 knaagbeest gunicorn[712]: Traceback (most recent call last):
Dec 15 01:09:48 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/engineio/server.py", line 595, in _trigger_event
Dec 15 01:09:48 knaagbeest gunicorn[712]:     return self.handlers[event](*args)
Dec 15 01:09:48 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/socketio/server.py", line 707, in _handle_eio_connect
Dec 15 01:09:48 knaagbeest gunicorn[712]:     self.manager.initialize()
Dec 15 01:09:48 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/socketio/redis_manager.py", line 65, in initialize
Dec 15 01:09:48 knaagbeest gunicorn[712]:     raise RuntimeError(
Dec 15 01:09:48 knaagbeest gunicorn[712]: RuntimeError: Redis requires a monkey patched socket library to work with eventlet
Dec 15 01:09:56 knaagbeest gunicorn[712]: Traceback (most recent call last):
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
Dec 15 01:09:56 knaagbeest gunicorn[712]:     timer()
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/hubs/timer.py", line 59, in __call__
Dec 15 01:09:56 knaagbeest gunicorn[712]:     cb(*args, **kw)
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/semaphore.py", line 152, in _do_acquire
Dec 15 01:09:56 knaagbeest gunicorn[712]:     waiter.switch()
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/greenlet.py", line 858, in gevent._gevent_cgreenlet.Greenlet.run
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/greenlet.py", line 829, in gevent._gevent_cgreenlet.Greenlet.__report_result
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/_gevent_cgreenlet.pxd", line 45, in gevent._gevent_cgreenlet.get_my_hub
Dec 15 01:09:56 knaagbeest gunicorn[712]: TypeError: Cannot convert greenlet.greenlet to gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop
Dec 15 01:09:56 knaagbeest gunicorn[712]: Traceback (most recent call last):
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
Dec 15 01:09:56 knaagbeest gunicorn[712]:     timer()
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/hubs/timer.py", line 59, in __call__
Dec 15 01:09:56 knaagbeest gunicorn[712]:     cb(*args, **kw)
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "/usr/lib/python3.9/site-packages/eventlet/semaphore.py", line 152, in _do_acquire
Dec 15 01:09:56 knaagbeest gunicorn[712]:     waiter.switch()
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/greenlet.py", line 858, in gevent._gevent_cgreenlet.Greenlet.run
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/greenlet.py", line 829, in gevent._gevent_cgreenlet.Greenlet.__report_result
Dec 15 01:09:56 knaagbeest gunicorn[712]:   File "src/gevent/_gevent_cgreenlet.pxd", line 45, in gevent._gevent_cgreenlet.get_my_hub
Dec 15 01:09:56 knaagbeest gunicorn[712]: TypeError: Cannot convert greenlet.greenlet to gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop
```

The last version which is working is 0.26.1-1.

**Comment by temoto** [comment]
@mischa85 there are both eventlet and gevent in traceback, that's probably sign of bad code/config. Please give minimal reproduction code.

**Comment by temoto** [comment]
Please reopen if/when there's a known way to reproduce the problem.

**Comment by ayushpratap17** [comment]
@mischa85 Did this issue get resolved? 
I'm occassionally getting the same error "Cannot convert greenlet.greenlet to gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop" when trying to kill a greenlet spawned using gevent.

**Comment by temoto** [comment]
@ayushpratap17 gevent is a different project here https://github.com/gevent/gevent
