### ISSUE TITLE
Logging failure when patching builtins on python 3.7.7 (patched open() doesn't take keyword arguments)

### ISSUE THREAD

**Issue by timt8** [eventlet/eventlet#683]
Running python 3.7.7, and monkey patching `builtins`, I see the following exception when configuring logging.
Looks like the patched `open()` call should take in keyword args?

    In setup logging
    Traceback (most recent call last):
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/config.py", line 563, in configure
        handler = self.configure_handler(handlers[name])
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/config.py", line 736, in configure_handler
        result = factory(**kwargs)
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/handlers.py", line 148, in __init__
        BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/handlers.py", line 55, in __init__
        logging.FileHandler.__init__(self, filename, mode, encoding, delay)
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/__init__.py", line 1087, in __init__
        StreamHandler.__init__(self, self._open())
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/__init__.py", line 1116, in _open
        return open(self.baseFilename, self.mode, encoding=self.encoding)
    TypeError: open() got an unexpected keyword argument 'encoding'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "./test.py", line 46, in <module>
        setup_logging()
      File "./test.py", line 43, in setup_logging
        logging.config.dictConfig(logging_dict)
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/config.py", line 800, in dictConfig
        dictConfigClass(config).configure()
      File "/Users/tim/.pyenv/versions/3.7.7/lib/python3.7/logging/config.py", line 571, in configure
        '%r' % name) from e
    ValueError: Unable to configure handler 'file'

Script used to reproduce:

    #!/usr/bin/env python

    import eventlet
    eventlet.monkey_patch(os=True,
                          select=True,
                          socket=True,
                          thread=True,
                          psycopg=True,
                          time=True,
                          builtins=True)

    import logging.config

    logging_dict = {
        'version': 1,
        'loggers': {
                '': {
                    'level': 'INFO',
                   'handlers': ['file'],
                   'propagate': False
                },
        },
        'handlers': {
                'file': {
                    'class': 'logging.handlers.RotatingFileHandler',
                    'level': 'INFO',
                    'formatter': 'detailed',
                    'filename': '/tmp/foo.log',
                    'mode': 'a',
                    'maxBytes': 10485760,
                    'backupCount': 9,
               },
        },
        'formatters': {
                'detailed': {
                    'format': '%(asctime)s [%(name)s|%(process)d|%(thread)d|%(threadName)s] | %(filename)s:%(funcName)s:(lineno)d (%(levelname)s) - %(message)s'  # noqa: E501
                }
        }
    }

    def setup_logging():
        print('In setup logging')
        logging.config.dictConfig(logging_dict)

    if __name__ == "__main__":
        setup_logging()`

**Comment by temoto** [comment]
@timt8 fix is merged into master. Please, try again with latest code.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by timt8** [comment]
Thank you so much @temoto!  Will this be included in an upcoming release?  I may have missed it, but I don't think I saw the changes in the latest (0.30.0) release.

**Comment by temoto** [comment]
@timt8 it's in v0.30.1
