### ISSUE TITLE
Compatibility with Python 3.10: TypeError: can't set attributes of built-in/extension type 'TimeoutError'

### ISSUE THREAD

**Issue by hrnciar** [eventlet/eventlet#687]
Hello,

it seems that there is minor incompatibility with Python 3.10 (currently alpha 5).

~~~~
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.10/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/builddir/build/BUILD/eventlet-0.30.1/doc/conf.py", line 52, in <module>
    import eventlet
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/builddir/build/BUILD/eventlet-0.30.1/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: can't set attributes of built-in/extension type 'TimeoutError'
~~~~

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1913291

**Comment by bibajz** [comment]
Hello, I would like to chime in here and point out that `eventlet` seems to be unable to start up as of `3.10.0b1` and, more precisely, since intorduction of [bpo43908](https://bugs.python.org/issue43908), which made a lot of built-ins immutable:

```
Python 3.10.0b1 (default, May 13 2021, 16:47:09) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/build/p310/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/build/p310/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/build/p310/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/build/p310/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/build/p310/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/build/p310/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/build/p310/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```

**Comment by apevec** [comment]
Is there a plan to avoid modifying immutable types in Eventlet?

**Comment by temoto** [comment]
@apevec yes. Also you can be the first to address this issue.

**Comment by vstinner** [comment]
> since intorduction of bpo43908, which made a lot of built-ins immutable

This issue is unrelated: it makes sure that immutable types in Python 3.9 remain immutable in Python 3.10.

socket.timeout became immutable in Python 3.10 for another reason: socket.timeout became an alias to the built-in TimeoutError exception.

* https://github.com/python/cpython/commit/03c8ddd9e94c7bddf1f06cf785027b8d2bf00ff0
* https://bugs.python.org/issue42413

> Is there a plan to avoid modifying immutable types in Eventlet?

wrap_is_timeout() and is_timeout() in eventlet/timeout.py could store is_timeout=True outside the class: in a separated private dictionary instead. I don't know if it would be worth it to use a weakref.WeakKeyDictionary.
https://docs.python.org/dev/library/weakref.html#weakref.WeakKeyDictionary

Do you expect wrap_is_timeout() to be used outside eventlet on objects which may be deleted before Python exit? If yes, a WeakKeyDictionary would be helpful.

**Comment by aentwist** [comment]
Python 3.10 was just released on October 4th. My app broke with the same issue @bibajz [mentioned above](https://github.com/eventlet/eventlet/issues/687#issuecomment-840664753) because my Docker image `python:3` updated from the `python:3.9` ref to `python:3.10`. I am pinning the version down to 3.9 until this gets fixed. This looks like it might be stale or low priority, so please let us know if there are any updates - thank you!

**Comment by fabswt** [comment]
This shouldn't be closed. eventlet is not compatible with Python 3.10. Please see https://github.com/eventlet/eventlet/issues/702

**Comment by tushgaurav** [comment]
Does not work on Python 3.13

**Comment by 4383** [comment]
@tushgaurav which version of eventlet are you using?
