### ISSUE TITLE
monkey_patch causes issues with dns .local

### ISSUE THREAD

**Issue by ffleandro** [eventlet/eventlet#694]
I've seen several closed tickets about this issue, but I'm still facing it.

These are my versions for `eventlet` and `dnspython`:
```
Name: eventlet
Version: 0.30.2
Summary: Highly concurrent networking library
Home-page: http://eventlet.net
Author: Linden Lab
Author-email: eventletdev@lists.secondlife.com
License: UNKNOWN
Location: /usr/local/lib/python3.8/site-packages
Requires: six, dnspython, greenlet
Required-by:
---
Name: dnspython
Version: 1.16.0
Summary: DNS toolkit
Home-page: http://www.dnspython.org
Author: Bob Halley
Author-email: halley@dnspython.org
License: BSD-like
Location: /usr/local/lib/python3.8/site-packages
Requires:
Required-by: eventlet
```

Easily reproducible by running:

```
import eventlet
import socket

eventlet.monkey_patch()
socket.gethostbyname('homeassistant.local')
```

Error log:
```
Python 3.8.2 (default, Apr  7 2020, 23:42:20)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> import socket
>>> eventlet.monkey_patch()
>>> socket.gethostbyname('homeassistant.local')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 426, in resolve
    return _proxy.query(name, rdtype, raise_on_no_answer=raises,
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 382, in query
    return end()
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 361, in end
    raise result[1]
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 342, in step
    a = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dns/resolver.py", line 1002, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: homeassistant.local., homeassistant.local.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 552, in gethostbyname
    rrset = resolve(hostname)
  File "/usr/local/lib/python3.8/site-packages/eventlet/support/greendns.py", line 436, in resolve
    raise EAI_NODATA_ERROR
socket.gaierror: [Errno -2] Name or service not known
```

Without monkey_patch everything works fine.
Any hints?

**Comment by ffleandro** [comment]
So it looks like `dnspython` doesn't support multicast-DNS: https://github.com/rthalley/dnspython/issues/653
So monkey patching eventlet without socket solved this for me, but I'm wondering if this is the correct solution or if we should handle this internally in eventlet, so leaving this issue open for evaluation.

Workaround:
```
import socket
import eventlet
eventlet.monkey_patch(socket=False)
socket.gethostbyname('homeassistant.local')
```

**Comment by temoto** [comment]
Mixture of:
- feature request for dnspython to support mdns -- best long term solution
- feature request Eventlet patches DNS resolving with another library that supports mdns
- feature request Eventlet patches all other socket functions except DNS resolving -- most productive short term workaround
- feature request Eventlet patches resolving functions to call system resolver via our built-in thread pool -- probably good idea

@eventlet/developers 

You gain most benefit from green threading in network (socket) because it is the most concurrent IO subsystem. `socket` is the main patching target, everything else is complementary. For most users, `monkey_patch(socket=False)` would be very similar to not patch at all.

## Workarounds

Is it possible to split DNS resolving and connection in your application? If yes, do monkey_patch, then call `eventlet.patcher.original("socket").gethostbyname("foo.local")` *every time before connection* and then connect normally.

Try `concurrent.futures.ThreadPoolExecutor` or `eventlet.tpool` without patching.

**Comment by ffleandro** [comment]
`eventlet.patcher.original("socket").gethostbyname("foo.local")`  worked for my use case.
Thanks a lot for the quick reply!
