### ISSUE TITLE
dns.name.LabelTooLong: A DNS label is > 63 octets long.

### ISSUE THREAD

**Issue by joncage** [eventlet/eventlet#698]
I have a flask based app (https://github.com/joncage/ed-scout) which uses eventlet and for the most part, works very well. I've just had a user report it doesn't start on their machine due to a dns name being too long:

```python
D:\Archives\Games\EDScout>EDScout.exe
Traceback (most recent call last):
  File "dns\name.py", line 149, in encode
  File "c:\python37\lib\encodings\idna.py", line 76, in ToASCII
  File "c:\python37\lib\encodings\idna.py", line 38, in nameprep
UnicodeError: Invalid character '\uedc1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EDScoutWebUI\EDScout.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "flask_socketio\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "socketio\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "socketio\zmq_manager.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\convenience.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\green\socket.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\jon\.virtualenvs\edscout-yes4e1p6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "eventlet\support\greendns.py", line 399, in <module>
  File "eventlet\support\greendns.py", line 313, in __init__
  File "eventlet\support\greendns.py", line 316, in clear
  File "dns\resolver.py", line 543, in __init__
  File "dns\resolver.py", line 702, in read_registry
  File "dns\resolver.py", line 682, in _config_win32_fromkey
  File "dns\resolver.py", line 648, in _config_win32_search
  File "dns\name.py", line 889, in from_text
  File "dns\name.py", line 853, in from_unicode
  File "dns\name.py", line 151, in encode
dns.name.LabelTooLong: A DNS label is > 63 octets long.
```

As far as I can tell, this is a bug in dnspython that has since been fixed but if I try and switch to a more recent version of `dnspython` I get this:

```python
  dnspython<2.0.0,>=1.15.0 (from eventlet==0.30.2->-r C:\Users\Jon\AppData\Local\Temp\pipenvarni5tn2requirements\pipenv-rdizh6zh-constraints.txt (line 5))
```

Is there a reason we can't use a more recent version of dns python?

**Comment by temoto** [comment]
Yes, reason is Eventlet is currently incompatible with dnspython>=2.0 you can read more or subscribe for updates here https://github.com/eventlet/eventlet/issues/619

Sorry.
