### ISSUE TITLE
Issues when importing requests with import_patched after importing normally

### ISSUE THREAD

**Issue by graingert** [eventlet/eventlet#7]
Not sure if this is requests fault or eventlets

``` python
graingert@MS-7681-ubu:~$ python
Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import eventlet
>>> eventlet.import_patched("requests")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 110, in import_patched
    *additional_modules + tuple(kw_additional_modules.items()))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 84, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from . import utils
ImportError: cannot import name utils
>>> import urllib2
>>> eventlet.import_patched("urllib2")
<module 'urllib2' from '/usr/lib/python2.7/urllib2.pyc'>
>>> 
graingert@MS-7681-ubu:~$ python
Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> eventlet.import_patched("requests")
<module 'requests' from '/usr/local/lib/python2.7/dist-packages/requests/__init__.pyc'>
>>> 
```

**Comment by frexvahi** [comment]
I got another error which is probably related to this one - here is a code sample:
```python
## __init__.py
import eventlet
eventlet.monkey_patch()

## some module that gets imported first
requests_in_other_module = eventlet.import_patched('requests')

## Library code (simplified from https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L270)
import requests
import requests.exceptions

try:
    requests.get('http://localhost:1')  # raises ConnectionError
except requests.exceptions.ConnectionError as e:
    print('Got ConnectionError:', e.args)
```

Somehow the `import requests.exceptions` does not add the `requests.exceptions` module as an attribute of the `requests` module:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2dba802e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple.py", line 13, in <module>
    except requests.exceptions.ConnectionError as e:
AttributeError: module 'requests' has no attribute 'exceptions'
```

**Comment by sangyu1996** [comment]
> I got another error which is probably related to this one - here is a code sample:
> 
> ```python
> ## __init__.py
> import eventlet
> eventlet.monkey_patch()
> 
> ## some module that gets imported first
> requests_in_other_module = eventlet.import_patched('requests')
> 
> ## Library code (simplified from https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L270)
> import requests
> import requests.exceptions
> 
> try:
>     requests.get('http://localhost:1')  # raises ConnectionError
> except requests.exceptions.ConnectionError as e:
>     print('Got ConnectionError:', e.args)
> ```
> 
> Somehow the `import requests.exceptions` does not add the `requests.exceptions` module as an attribute of the `requests` module:
> 
> ```
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2dba802e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "simple.py", line 13, in <module>
>     except requests.exceptions.ConnectionError as e:
> AttributeError: module 'requests' has no attribute 'exceptions'
> ```

I also met this problem, have you solved it?
