### ISSUE TITLE
gunicorn eventlet worker requires eventlet 0.24.1 or higher

### ISSUE THREAD

**Issue by DimitarDevP** [eventlet/eventlet#734]
I have been trying to reconfigure my deployment and move from uWSGI to gunicorn. I was going through the tutorial on how to do this and did everything as per the protocol. When I tried to start the server using the following command:
`unicorn -b 0.0.0.0:$PORT main:app --workers 2 --worker-class eventlet --reload --preload`

I got the following response:
```
Error: class uri 'eventlet' invalid or not found: 

[Traceback (most recent call last):
  File "/home/dimitar/.local/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 12, in <module>
    import eventlet
ModuleNotFoundError: No module named 'eventlet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dimitar/.local/lib/python3.9/site-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dimitar/.local/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 14, in <module>
    raise RuntimeError("eventlet worker requires eventlet 0.24.1 or higher")
RuntimeError: eventlet worker requires eventlet 0.24.1 or higher
]
```
I tried to play around with the versions. I followed [this issue](https://github.com/eventlet/eventlet/issues/702) and installed the instructed versions of `gunicorn` and `eventlet` but that didnt solve my problem.

Any suggestions?

**Comment by temoto** [comment]
Please show installation from start.

**Comment by DimitarDevP** [comment]
It works on the server, it was just my machine that had conflicting versions apparently.

**Comment by temoto** [comment]
Cool, I had issues with --user too. Virtualenv works every time.

**Comment by DimitarDevP** [comment]
Usually versions are the most common issue, it would be of great help to create templates with working environments for Flask, Django and what not so that we (as developers) can just clone and build upon them but I guess that is up to the community and not the developers who develop the different packages. In my case, it would have saved me 4 and a half hours of setup.

**Comment by temoto** [comment]
@DimitarDevP please describe interface to such templates. Imagine it's done and show shell commands/results how you use them.
