### ISSUE TITLE
dns.resolver.NoResolverConfiguration on importing eventlet

### ISSUE THREAD

**Issue by dtantsur** [eventlet/eventlet#736]
Hi! We have an environment which is inside a service ramdisk, so working DNS is not assumed. Starting with presumably 0.32.0 eventlet cannot be imported:
```
Traceback (most recent call last):
  File "/usr/local/bin/ironic-python-agent", line 5, in <module>
    from ironic_python_agent.cmd.agent import run
  File "/usr/local/lib/python3.6/site-packages/ironic_python_agent/__init__.py", line 15, in <module>
    import eventlet
  File "/usr/local/lib/python3.6/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.6/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python3.6/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/usr/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 411, in <module>
    resolver = ResolverProxy(hosts_resolver=HostsResolver())
  File "/usr/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 325, in __init__
    self.clear()
  File "/usr/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 328, in clear
    self._resolver = dns.resolver.Resolver(filename=self._filename)
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 734, in __init__
    self.read_resolv_conf(filename)
  File "/usr/local/lib/python3.6/site-packages/dns/resolver.py", line 826, in read_resolv_conf
    raise NoResolverConfiguration
dns.resolver.NoResolverConfiguration: Resolver configuration could not be read or specified no nameservers.
```

This issue has initially surfaces in https://github.com/eventlet/eventlet/issues/462, but it's a feature request, while this problem is a serious blocker for us in OpenStack Ironic.

**Comment by dtantsur** [comment]
The same issue reported in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2017933
