### ISSUE TITLE
test_017_ssl_zeroreturnerror raises SSLEOFError on Python 3.10

### ISSUE THREAD

**Issue by foutrelis** [eventlet/eventlet#739]
First noticed in https://github.com/eventlet/eventlet/pull/715#discussion_r650300750 -- thought I'd file an issue for it.

This and https://github.com/eventlet/eventlet/issues/730 are the only issues failing for us on Arch Linux with Python 3.10.

```
Traceback (most recent call last):
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/tests/wsgi_test.py", line 566, in server
    serv.process_request([addr, client_socket, wsgi.STATE_IDLE])
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/eventlet/wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/eventlet/wsgi.py", line 352, in __init__
    self.finish()
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/eventlet/wsgi.py", line 751, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/usr/lib/python3.10/socketserver.py", line 811, in finish
    self.wfile.close()
  File "/usr/lib/python3.10/socket.py", line 723, in write
    return self._sock.send(b)
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/eventlet/green/ssl.py", line 194, in send
    return self._call_trampolining(
  File "/home/foutrelis/desktop/python-eventlet/trunk/src/eventlet-0.33.0/eventlet/green/ssl.py", line 162, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.10/ssl.py", line 1205, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)
```

**Comment by doko42** [comment]
I also see this with Python 3.11.3, but not with 3.11.2.  Applying the patch from #787 doesn't make a difference.
