### ISSUE TITLE
eventlet.wsgi.server can't work with SSL sockets?

### ISSUE THREAD

**Issue by bialix** [eventlet/eventlet#745]
I'm using python-socketio with eventlet. It works very well with plain sockets (http://). But I'd like to test it locally with https, so I'm trying to use ssl sockets.

I've tried to pass ordinary python socket wrapped into ssl context, but wsgi.server seems to just hang after connection was established. Although `openssl s_client` can successfully connect and check server's certificate.

So I've changed my code according to your example https://eventlet.net/doc/ssl.html

```
import socketio
from eventlet.green import socket
from eventlet.green.OpenSSL import SSL

sk = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

context = SSL.Context(SSL.SSLv23_METHOD)
context.use_privatekey_file('server.pem')
context.use_certificate_file('server.pem')

ssk = SSL.Connection(context, sk)
# configure as server
ssk.set_accept_state()
ssk.bind(('127.0.0.1', 10069))
ssk.listen(50)

app = socketio.WSGIApp(sio)
eventlet.wsgi.server(ssk, app)
```

This way it does not work at all - on every connection I see series of tracebacks. Starting with this:

```
Server initialized for eventlet.
(10604) wsgi starting up on https://127.0.0.1:10069
(10604) accepted ('127.0.0.1', 16848)
Traceback (most recent call last):
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\wsgi.py", line 367, in setup
    self.rfile = conn.makefile('rb', self.rbufsize)
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\green\OpenSSL\SSL.py", line 46, in makefile
    raise NotImplementedError("Makefile not supported on SSL sockets")
NotImplementedError: Makefile not supported on SSL sockets
```

During handling of this traceback another one occured:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\wsgi.py", line 348, in __init__
    self.setup()
  File "D:\work\ssl-server\venv\lib\site-packages\eventlet\wsgi.py", line 372, in setup
    self.rfile = socket._fileobject(conn, "rb", self.rbufsize)
AttributeError: module 'eventlet.green.socket' has no attribute '_fileobject'
```

I'm testing on Windows, so I suppose you need some magic which is not available on Windows, right?
What can I do to make it work?

**Comment by bialix** [comment]
I've checked on Centos 7.9 with Python 3.6.8 - the same error.

```
[bialix@rpmbuild-dev 3]$ ./venv/bin/python sessmgr-server.py
Server initialized for eventlet.
(27864) wsgi starting up on https://0.0.0.0:10069
(27864) accepted ('192.168.23.120', 1325)
Traceback (most recent call last):
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 367, in setup
    self.rfile = conn.makefile('rb', self.rbufsize)
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/green/OpenSSL/SSL.py", line 46, in makefile
    raise NotImplementedError("Makefile not supported on SSL sockets")
NotImplementedError: Makefile not supported on SSL sockets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 837, in process_request
    proto.__init__(conn_state, self)
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 348, in __init__
    self.setup()
  File "/home/bialix/3/venv/lib/python3.6/site-packages/eventlet/wsgi.py", line 372, in setup
    self.rfile = socket._fileobject(conn, "rb", self.rbufsize)
AttributeError: module 'eventlet.green.socket' has no attribute '_fileobject'
```
