### ISSUE TITLE
Adding requests as a dependency to flask app causes gunicorn+eventlet to fail with a bad file descriptor

### ISSUE THREAD

**Issue by christophevg** [eventlet/eventlet#779]
Hi, 

when adding `requests` to the environment where a `flask` app is run using `gunicorn` + `eventlet`, the setup won't start up anymore, failing with a bad file descriptor error.

Environment

```console
% uname -a
Darwin sokudo.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

% python -V
Python 3.8.12
```

Steps to reproduce:

```console
% pip freeze

% cat requirements.txt 
flask
eventlet==0.33.2
gunicorn @ https://github.com/benoitc/gunicorn/archive/ff58e0c6da83d5520916bc4cc109a529258d76e1.zip
# the specific gunicorn version is needed to overcome: https://stackoverflow.com/questions/67409452/gunicorn-importerror-cannot-import-name-already-handled-from-eventlet-wsgi

% pip install -r requirements.txt 
...
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 click-8.1.3 dnspython-2.2.1 eventlet-0.33.2 flask-2.2.2 greenlet-2.0.1 gunicorn-20.1.0 importlib-metadata-6.0.0 itsdangerous-2.1.2 six-1.16.0 zipp-3.11.0

% cat test.py 
from flask import Flask
server = Flask(__name__)

% gunicorn -k eventlet -w 1 test:server
[2023-01-07 20:33:03 +0100] [31717] [INFO] Starting gunicorn 20.1.0
[2023-01-07 20:33:03 +0100] [31717] [INFO] Listening at: http://127.0.0.1:8000 (31717)
[2023-01-07 20:33:03 +0100] [31717] [INFO] Using worker: eventlet
[2023-01-07 20:33:03 +0100] [31731] [INFO] Booting worker with pid: 31731

^C
[2023-01-07 20:33:04 +0100] [31717] [INFO] Handling signal: int
[2023-01-07 20:33:05 +0100] [31731] [INFO] Worker exiting (pid: 31731)
[2023-01-07 20:33:05 +0100] [31717] [INFO] Shutting down: Master
```

This is the working minimal setup. 
Now, adding `requests`:

```console
% pip install requests
...
Successfully installed certifi-2022.12.7 charset-normalizer-2.1.1 idna-3.4 requests-2.28.1 urllib3-1.26.13

% gunicorn -k eventlet -w 1 test:server
[2023-01-07 20:37:43 +0100] [31909] [INFO] Starting gunicorn 20.1.0
[2023-01-07 20:37:43 +0100] [31909] [INFO] Listening at: http://127.0.0.1:8000 (31909)
[2023-01-07 20:37:43 +0100] [31909] [INFO] Using worker: eventlet
[2023-01-07 20:37:43 +0100] [31923] [INFO] Booting worker with pid: 31923
Traceback (most recent call last):
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 83, in _eventlet_serve
    conn, addr = sock.accept()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/greenio/base.py", line 233, in accept
    self._trampoline(fd, read=True, timeout=self.gettimeout(), timeout_exc=_timeout_exc)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/greenio/base.py", line 211, in _trampoline
    return trampoline(fd, read=read, write=write, timeout=timeout,
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/__init__.py", line 155, in trampoline
    listener = hub.add(hub.READ, fileno, current.switch, current.throw, mark_as_closed)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/kqueue.py", line 53, in add
    self._control([event], 0, 0)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/kqueue.py", line 39, in _control
    return self.kqueue.control(events, max_events, timeout)
OSError: [Errno 9] Bad file descriptor
[2023-01-07 20:37:43 +0100] [31923] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 175, in run
    eventlet.sleep(1.0)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/greenthread.py", line 36, in sleep
    hub.switch()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 313, in switch
    return self.greenlet.switch()
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 365, in run
    self.wait(sleep_time)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/kqueue.py", line 98, in wait
    result = self._control([], self.MAX_EVENTS, seconds)
  File "/Users/xtof/.pyenv/versions/3.8.12/envs/temp/lib/python3.8/site-packages/eventlet/hubs/kqueue.py", line 39, in _control
    return self.kqueue.control(events, max_events, timeout)
OSError: [Errno 9] Bad file descriptor
[2023-01-07 20:37:43 +0100] [31923] [INFO] Worker exiting (pid: 31923)
...
```

Hopefully I missed something, else any other workaround/solution is very appreciated - since the requests dependency comes from another dependency, so I can't easily replace/remove it :-(

**Comment by christophevg** [comment]
Apparently, using the other workaround (see #702 ), pinning `eventlet` to `0.30.2` seems to avoid the problem.

Further steps:

```console
% pip install eventlet==0.30.2
...
Successfully installed dnspython-1.16.0 eventlet-0.30.2

% gunicorn -k eventlet -w 1 test:server
[2023-01-07 21:11:13 +0100] [38011] [INFO] Starting gunicorn 20.1.0
[2023-01-07 21:11:13 +0100] [38011] [INFO] Listening at: http://127.0.0.1:8000 (38011)
[2023-01-07 21:11:13 +0100] [38011] [INFO] Using worker: eventlet
[2023-01-07 21:11:13 +0100] [38025] [INFO] Booting worker with pid: 38025

^C
[2023-01-07 21:11:15 +0100] [38011] [INFO] Handling signal: int
[2023-01-07 21:11:16 +0100] [38025] [INFO] Worker exiting (pid: 38025)
[2023-01-07 21:11:16 +0100] [38011] [INFO] Shutting down: Master
```

And this solution seems rather to be addressed to the `dnspython` dependency, which is referenced in #619 it seems. Now, when pinning `dnspython` `<2.0.0`:

```console
% pip freeze

% cat requirements.txt 
flask
eventlet==0.33.2
gunicorn @ https://github.com/benoitc/gunicorn/archive/ff58e0c6da83d5520916bc4cc109a529258d76e1.zip
dnspython<2.0.0   # pinned due to #619 

% pip install -r requirements.txt 
...
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 click-8.1.3 dnspython-1.16.0 eventlet-0.33.2 flask-2.2.2 greenlet-2.0.1 gunicorn-20.1.0 importlib-metadata-6.0.0 itsdangerous-2.1.2 six-1.16.0 zipp-3.11.0

% pip install requests
...
Successfully installed certifi-2022.12.7 charset-normalizer-2.1.1 idna-3.4 requests-2.28.1 urllib3-1.26.13

% gunicorn -k eventlet -w 1 test:server
[2023-01-07 21:21:11 +0100] [40512] [INFO] Starting gunicorn 20.1.0
[2023-01-07 21:21:11 +0100] [40512] [INFO] Listening at: http://127.0.0.1:8000 (40512)
[2023-01-07 21:21:11 +0100] [40512] [INFO] Using worker: eventlet
[2023-01-07 21:21:11 +0100] [40526] [INFO] Booting worker with pid: 40526

^C
[2023-01-07 21:21:14 +0100] [40512] [INFO] Handling signal: int
[2023-01-07 21:21:14 +0100] [40526] [INFO] Worker exiting (pid: 40526)
[2023-01-07 21:21:15 +0100] [40512] [INFO] Shutting down: Master
```

This seems a possible doable workaround.
Is this the best approach?

**Comment by christophevg** [comment]
Seems this problem is resolved... All current versions work happily together again 😉

```console
% pip freeze

% cat requirements.txt 
flask
eventlet
gunicorn
requests

% pip install -r requirements.txt 
...
Successfully installed Jinja2-3.1.2 ...

 % cat test.py 
from flask import Flask
server = Flask(__name__)

% gunicorn -k eventlet -w 1 test:server
[2023-11-12 18:59:19 +0100] [2844] [INFO] Starting gunicorn 21.2.0
[2023-11-12 18:59:19 +0100] [2844] [INFO] Listening at: http://127.0.0.1:8000 (2844)
[2023-11-12 18:59:19 +0100] [2844] [INFO] Using worker: eventlet
[2023-11-12 18:59:19 +0100] [2871] [INFO] Booting worker with pid: 2871
```
