### ISSUE TITLE
0.33.3: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [eventlet/eventlet#785]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v6.1.3

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/conf.py", line 52, in <module>
    import eventlet
ModuleNotFoundError: No module named 'eventlet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 364, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/conf.py", line 52, in <module>
    import eventlet
ModuleNotFoundError: No module named 'eventlet'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/conf.py", line 52, in <module>
    import eventlet
ModuleNotFoundError: No module named 'eventlet'
```
</details>

This can be fixed by patch like below:
```patch
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -16,7 +16,7 @@
 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
-#sys.path.append(os.path.abspath('.'))
+sys.path.append(os.path.abspath(".."))

 # -- General configuration -----------------------------------------------------
```
Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

Here is the output with warnings:

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v6.1.3
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] zeromq
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/dagpool.rst:66: WARNING: Title underline too short.

Tutorial
*******
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/dagpool.rst:66: WARNING: Title underline too short.

Tutorial
*******
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.recv:1: WARNING: duplicate object description of eventlet.green.zmq.Socket.recv, other instance in modules/zmq, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.send:1: WARNING: duplicate object description of eventlet.green.zmq.Socket.send, other instance in modules/zmq, use :noindex: for one of them
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.send_multipart:25: ERROR: Unexpected indentation.
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of zmq.sugar.socket.Socket.send_serialized:9: ERROR: Unexpected indentation.
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/ssl.rst:72: WARNING: Literal block expected; none found.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-eventlet.3 { basic_usage design_patterns patching examples ssl threading zeromq hubs testing environment modules modules/backdoor modules/corolocal modules/dagpool modules/debug modules/db_pool modules/event modules/greenpool modules/greenthread modules/pools modules/queue modules/semaphore modules/timeout modules/websocket modules/wsgi modules/zmq authors history } /home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/basic_usage.rst:1: WARNING: py:meth reference target not found: GreenThread.cancel
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/design_patterns.rst:112: WARNING: py:func reference target not found: join
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/patching.rst:6: WARNING: py:mod reference target not found: thread
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/patching.rst:6: WARNING: py:mod reference target not found: Queue
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/ssl.rst:6: WARNING: py:mod reference target not found: eventlet.green.urllib2
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/ssl.rst:19: WARNING: py:mod reference target not found: eventlet.green.OpenSSL
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/ssl.rst:19: WARNING: py:func reference target not found: socket.ssl
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/backdoor.rst:1: WARNING: py:mod reference target not found: backdoor
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/corolocal.rst:1: WARNING: py:mod reference target not found: corolocal
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/dagpool.rst:1: WARNING: py:mod reference target not found: dagpool
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/dagpool.py:docstring of eventlet.dagpool.Collision:1: WARNING: py:meth reference target not found: eventlet.greenthread.GreenThread.imap
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/debug.rst:1: WARNING: py:mod reference target not found: debug
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/db_pool.rst:1: WARNING: py:mod reference target not found: db_pool
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/db_pool.rst:13: WARNING: py:meth reference target not found: eventlet.db_pool.ConnectionPool.get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/db_pool.py:docstring of eventlet.db_pool.BaseConnectionPool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/event.rst:1: WARNING: py:mod reference target not found: event
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/event.py:docstring of eventlet.event.Event:18: WARNING: py:meth reference target not found: reset
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/greenpool.rst:1: WARNING: py:mod reference target not found: greenpool
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenpool.py:docstring of eventlet.greenpool:1: WARNING: py:func reference target not found: itertools.imap
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenpool.py:docstring of eventlet.greenpool:1: WARNING: py:class reference target not found: eventlet.GreenThread
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/greenthread.rst:1: WARNING: py:mod reference target not found: greenthread
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenthread.py:docstring of eventlet.greenthread:1: WARNING: py:class reference target not found: greenlet.GreenletExit
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenthread.py:docstring of eventlet.greenthread:1: WARNING: py:class reference target not found: greenlet.GreenletExit
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenthread.py:docstring of greenlet._greenlet.getcurrent:1: WARNING: py:class reference target not found: greenlet
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/greenthread.py:docstring of eventlet.greenthread.GreenThread:1: WARNING: py:func reference target not found: greenthread.sleep
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/pools.rst:1: WARNING: py:mod reference target not found: pools
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/pools.py:docstring of eventlet.pools.Pool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/pools.py:docstring of eventlet.pools.Pool:1: WARNING: py:meth reference target not found: put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/pools.py:docstring of eventlet.pools.Pool:1: WARNING: py:meth reference target not found: get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:3: WARNING: py:mod reference target not found: Queue
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:8: WARNING: py:meth reference target not found: Queue.empty
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:8: WARNING: py:meth reference target not found: Queue.full
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:8: WARNING: py:meth reference target not found: Queue.put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:8: WARNING: py:meth reference target not found: Queue.get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.qsize
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.empty
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.full
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.getting
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.putting
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:13: WARNING: py:meth reference target not found: Queue.get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:1: WARNING: py:class reference target not found: Stdlib_Queue
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:1: WARNING: py:meth reference target not found: Stdlib_Queue.task_done
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:1: WARNING: py:meth reference target not found: Stdlib_Queue.join
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:2: WARNING: py:meth reference target not found: put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:2: WARNING: py:class reference target not found: Stdlib_Queue
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:6: WARNING: py:class reference target not found: Stdlib_Queue
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:1: WARNING: py:meth reference target not found: Queue.get
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/queue.py:docstring of eventlet.queue:2: WARNING: py:meth reference target not found: Queue.put
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/semaphore.rst:1: WARNING: py:mod reference target not found: semaphore
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/timeout.rst:1: WARNING: py:mod reference target not found: timeout
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/timeout.rst:9: WARNING: py:class reference target not found: Timeout
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/timeout.rst:: WARNING: more than one target found for cross-reference 'Timeout': eventlet.Timeout, eventlet.timeout.Timeout
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/websocket.rst:1: WARNING: py:mod reference target not found: websocket
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/websocket.rst:9: WARNING: py:class reference target not found: WebSocketWSGI
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:1: WARNING: py:mod reference target not found: wsgi
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/wsgi.py:docstring of eventlet.wsgi.format_date_time:1: WARNING: py:class reference target not found: greenlet.GreenletExit
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:93: WARNING: py:func reference target not found: set_hundred_continue_response_header
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:113: WARNING: py:func reference target not found: test_024a_expect_100_continue_with_headers
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:123: WARNING: py:func reference target not found: send_hundred_continue_response
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:126: WARNING: py:func reference target not found: test_024b_expect_100_continue_with_headers_multiple_chunked
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/doc/modules/wsgi.rst:126: WARNING: py:func reference target not found: test_024c_expect_100_continue_with_headers_multiple_nonchunked
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Context:1: WARNING: py:class reference target not found: zmq.sugar.context.Context
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Context:1: WARNING: py:class reference target not found: zmq.Context
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Context.socket:1: WARNING: py:meth reference target not found: zmq.Context.socket
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: zmq.sugar.socket.Socket
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.recv:1: WARNING: py:class reference target not found: ZMQError
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.recv:1: WARNING: py:class reference target not found: Poller
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.send:1: WARNING: py:class reference target not found: ZMQError
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket.send:1: WARNING: py:class reference target not found: Poller
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of zmq.sugar.socket.Socket.get_monitor_socket:1: WARNING: py:class reference target not found: zmq.sugar.socket.T
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: Poller
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: ZMQError
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: Poller
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: ZMQError
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of eventlet.green.zmq.Socket:1: WARNING: py:class reference target not found: Poller
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of zmq.sugar.socket.Socket.send_string:1: WARNING: py:class reference target not found: zmq.sugar.frame.Frame
/home/tkloczko/rpmbuild/BUILD/eventlet-0.33.3/eventlet/green/zmq.py:docstring of zmq.sugar.socket.Socket.shadow:1: WARNING: py:class reference target not found: zmq.sugar.socket.T
done
build succeeded, 96 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/frostming/unearth/issues/14
https://github.com/pypa/distlib/commit/98b9b89f

**Comment by temoto** [comment]
> First of all currently it is not possible to use straight sphinx-build command to build documentation out of source tree

It was never intended, just like running pytest or anything else out of tree. I can see how generating website could be useful for distributing documentation.

Maybe we can settle on something like `tox -e build-website`, it will run pinned sphinx or whatever is currently used and produce artifact in hardcoded location like `${repo}/website-build` possibly shadowed by env like `target=/out tox -e build-website`

**Comment by temoto** [comment]
Only later I realized it was about special man output format, so everything above with `s/build-website/build-man/g`.

**Comment by kloczek** [comment]
> Maybe we can settle on something like `tox -e build-website`, it will run pinned sphinx or whatever is currently used and produce artifact in hardcoded location like `${repo}/website-build` possibly shadowed by env like `target=/out tox -e build-website`

Thing is that as long as you have installed all necessary odules and `sys.path` is alterd you don't need to use `tox` or you don't need to install module 😃 
Documentation can be generated out of freshly cloned repo as well 😄

**Comment by kloczek** [comment]
> Anyhow, patches on broken refs are very welcome. I can't put time in doc before 3.10+ support. Thanks for that sys.path fix, seems obviously required there.

I'm only interested roff output which is not affected by broken refs.
However on review package I'm trying to provide all possible feedbacks about what I'm able to spot.
Sorry but I have really long queue of other modules to cleanup .. maybe later 😞

**Comment by temoto** [comment]
> Thing is that as long as you have installed all necessary odules and sys.path is alterd you don't need to use tox or you don't need to install module 

Yes.

`tox -e build-man` or similar project command is an API, a contract: produce a useful artifact given minimal python environment, while not touching global packages.

It doesn't have to be tox. It just has to be works anywhere single button. Currently `bin/build-website.bash` is expecting to be run from virtualenv with sphinx installed. `bin/build-website.bash` would be that single button if it managed sphinx for itself.

**Comment by kloczek** [comment]
In my build I'm using pytest only because it allows alter test suite execution by install additionall pytest extensios.
```console
[tkloczko@devel-g2v SPECS]$ grep ^%pytest python-*.spec | wc -l; grep ^%tox python-*.spec | wc -l; ls -1 python-*.spec |wc -l
1060
0
1080
```
By this I'm able to perfom kind of side builds in which in build env is for exampe installed `randomly`, `blak` or `pytest-benchmark` and check which one modules test suite have broken test suite (by have dependencies between units) or which one modules have code formated using `black`, or collect additional data about units performance and compare that with prev builds .. all that without touching rpm spec file sused to build python module.
With `tox` it is no possibe because it executes ezact target in set of fixed env.

**Comment by temoto** [comment]
@kloczek yeah project metrics is great fun. True version of randomly (ignore file/class boundary) should be the only possible mode to run tests.

Environment pinning is intentional and would be done by another tool if not tox. To be compatible with open set of dependencies is really cool, but also a lot of work. Eventlet does not support pytest so far. Please subscribe at https://github.com/eventlet/eventlet/issues/638 to track progress.
