### ISSUE TITLE
OSError: Load averages are unobtainable

### ISSUE THREAD

**Issue by PShravan** [eventlet/eventlet#806]
`Traceback (most recent call last):
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/hubs/timer.py", line 59, in __call__
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/greenthread.py", line 224, in main
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/greenthread.py", line 240, in _resolve_links
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/celery/concurrency/eventlet.py", line 62, in _entry_exit
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/greenthread.py", line 181, in wait
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/event.py", line 132, in wait
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/eventlet/greenthread.py", line 221, in main
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/kombu/asynchronous/timer.py", line 70, in __call__
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/kombu/asynchronous/timer.py", line 137, in _reschedules
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/celery/worker/heartbeat.py", line 45, in _send
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/celery/utils/sysinfo.py", line 23, in load_average
  File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/celery/utils/sysinfo.py", line 13, in _load_average
OSError: Load averages are unobtainable`

Our django celery server is running with concurrency value of 500 with Eventlet as execution pool. Recently, we encountered this error and restarting the celery fixed it. Is this an issue with eventlet or due to some incorrect implementation from our end? Any solution to fix this?

python package versions: Django 4.1.7 celery 5.2.3 eventlet 0.33.3

**Comment by radeksm** [comment]
@PShravan your error comes from celery 
`File "/home/ubuntu/project_data/venv/lib/python3.10/site-packages/celery/utils/sysinfo.py", line 13, in _load_average OSError: Load averages are unobtainable` 
when celery calls `tuple(ceil(l * 1e2) / 1e2 for l in os.getloadavg())`
OSError can be raised when os.getloadavg() is unable to get the load value for whatever reason.
IMHO, it could be a file descriptor limit which you hit while getloadavg() is trying to read /proc/loadavg file.
