### ISSUE TITLE
Is there any solution to use counterfit without any error in python version 3.12.2?  AttributeError: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by mahabubamou12** [eventlet/eventlet#914]
(.venv) C:\Users\mahab\nightlight>counterfit --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mahab\nightlight\.venv\Scripts\counterfit.exe\__main__.py", line 4, in <module>
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\CounterFit\counterfit.py", line 11, in <module>
    from eventlet import event
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\eventlet\support\greendns.py", line 45, in <module>
    from eventlet.green import ssl
  File "C:\Users\mahab\nightlight\.venv\Lib\site-packages\eventlet\green\ssl.py", line 25, in <module>
    _original_wrap_socket = __ssl.wrap_socket
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Comment by 4383** [comment]
@mahabubamou12: any updates?

**Comment by 4383** [comment]
Looks related to #795

**Comment by 4383** [comment]
Any update?

**Comment by ak4153** [comment]
I had the same problem taking eventlet code and placing it in a Higha library.
OP just update eventlet since wrap_socket is now part of SSLContext.
`SSLContext.wrap_socket()`
