### ISSUE TITLE
eventlet asyncio hub does not run as documented

### ISSUE THREAD

**Issue by yury-ppl-ai** [eventlet/eventlet#929]
Hi, I am trying to run the examples on the eventlet.net website. I am using eventlet==0.35.2 with Python 3.10.13. I have the same problem with master and Python 3.11.7.

While it is not copied verbatim from the website (that obviously will not run), I think it is very close.
```
import eventlet
import eventlet.hubs
eventlet.hubs.use_hub("eventlet.hubs.asyncio")

eventlet.monkey_patch()

import aiohttp
from eventlet.asyncio import spawn_for_awaitable

async def request():
    async with aiohttp.ClientSession() as session:
        url = "https://example.com"
        async with session.get(url) as response:
            html = await response.text()
            return html

# You can wrap this coroutine with an Eventlet GreenThread, similar to
# ``evenlet.spawn()``:
gthread = spawn_for_awaitable(request())

# And then get its result, the body of https://example.com:
result = gthread.wait()
print(result)
```

This raises an assertion:
```
Traceback (most recent call last):
  File "/Users/yury/workspace/agi/eventlet_asyncio2.py", line 22, in <module>
    result = gthread.wait()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 224, in wait
    return self._exit_event.wait()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/event.py", line 124, in wait
    result = hub.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 310, in switch
    return self.greenlet.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 264, in main
    result = function(*args, **kwargs)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/asyncio.py", line 54, in _run
    return future.result()
  File "/Users/yury/workspace/agi/eventlet_asyncio2.py", line 13, in request
    async with session.get(url) as response:
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 940, in start
    self._started.wait()
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/semaphore.py", line 115, in acquire
    hubs.get_hub().switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 297, in switch
    assert cur is not self.greenlet, 'Cannot switch to MAINLOOP from MAINLOOP'
AssertionError: Cannot switch to MAINLOOP from MAINLOOP
```

The only real difference between this code and the example code is that I added the monkey-patch line. Am I misunderstanding the example? Is there something else I need to do?

**Comment by itamarst** [comment]
Hi, thanks for the detailed bug report, we'll try to look at it next week. Note that we do not recommend using eventlet for any new projects, the goal of the asyncio hub is to help migrate off of eventlet.

**Comment by yury-ppl-ai** [comment]
Yes, that is exactly what I am trying to do. Unfortunately, the codebase is a little large so rewriting everything in asyncio in one go is not feasible. I tried dropping the asyncio hub into the project, but that exploded with many exceptions. I then tried a few simpler examples. I was able to run a very simple async function (asyncio.sleep), but nothing more complicated.

**Comment by 4383** [comment]
Hello, if I removes the eventlet monkey patch from your example, or if I move it at the end of the code, your code snippet runs is ok.

So, as far as I can see, the monkey patch should be made after all the asyncio.

I think you have to ensure that in your application, all the asyncio migrated code is declared and triggered before the things you monkey patch. Monkey patching case by case could be a solution. Instead of relying on a global monkey patched application, it should be possible to monkey patch module by module, and then, isolate the part of your code you are currently migrating or who are already migrated.

But, please, lets Itamar give is observations before taking my comment as a solution.

**Comment by itamarst** [comment]
The specific traceback involves a DNS lookup. These are blocking by default, so involve a real thread pool... which is not something the current hub thinks about very much. So at minimum would need to figure out how to address that.

**Comment by itamarst** [comment]
OK here's a workaround, untested but based on a temporary fix I tried, after more investigation I will turn it into a PR hopefully today, maybe later in the week depending how I'm feeling.

```
import eventlet
import eventlet.hubs
eventlet.hubs.use_hub("eventlet.hubs.asyncio")

eventlet.monkey_patch()

# Make sure the thread pool used by asyncio or maybe aiohttp still uses real threads:
from eventlet.hubs import hub
from eventlet.patcher import original
concurrent.futures.thread.threading = original("threading")
concurrent.futures.thread.queue = original("queue")

# ... rest of the code...
```

**Comment by 4383** [comment]
Depending on context, greenthread and monkey patching can quickly become a nightmare... Several years ago, on Openstack, we faced the same kind of issue [1] by using or not monkey patched threads when running a rabbitmq heartbeat. Due to HTTPD mod_wsgi and to  parked requests [1]. I wrote a fix [2] to move the heartbeat into a python thread rather than into a greenthread. 

Eventlet can poison your life by making you juggle between enabling and disabling native threading depending on contexts.

I think Itamar's suggestion is right, do not forget to unpatch queue, as he suggested, so queues are not going to
use greenthreads as well. That's important.

I'd suggest to isolate your asyncio code into a one or more dedicated submodules where you take care to use "original" and unpatched modules. Do not hesitate to take a look to the fix I refered to [2].

[1] https://bugs.launchpad.net/oslo.messaging/+bug/1934937/comments/3
[2] https://opendev.org/openstack/oslo.messaging/commit/22f240b82fffbd62be8568a7d0d3369134596ace

**Comment by itamarst** [comment]
I _think_ this is pretty fundamental asyncio future (a built-in thread pool is typical for event loops) but I haven't validated. If it is, this is something we should fix.

**Comment by 4383** [comment]
Yeah, could be fixed at the asyncio hub level, to set up the right base environment automatically.

**Comment by 4383** [comment]
Also, on specific asyncio based code I don't think we need a monkey patched env at all. Unfortunately, as far as I know such commands like revert_monkey doesn't exists. Things needs to be reverted manually. Monkey patching should be only used with other hubs and IMO totally disabled for things launched with `spawn_for_awaitable` https://github.com/eventlet/eventlet/blob/master/eventlet/asyncio.py.

**Comment by itamarst** [comment]
It's... fairly difficult to limit monkey-patching to specific functions, unfortunately.

**Comment by itamarst** [comment]
The linked PR should hopefully get you past this issue. Please do let us know as you find more, getting asyncio working correctly for migration off-ramp is our top priority for Eventlet.

**Comment by yury-ppl-ai** [comment]
There seem to be some deeper problems. I am actually using httpx in my code, so I will use that in these examples. However, I see mostly the same thing with aiohttp.

Here are two samples of code:
Code A:
```
import eventlet
import eventlet.hubs
eventlet.hubs.use_hub("eventlet.hubs.asyncio")

# no monkey-patching at all

from eventlet.asyncio import spawn_for_awaitable

import httpx

async def request():
    async with httpx.AsyncClient() as client:
        response = await client.get('https://www.example.com/')
        return response.text

print(spawn_for_awaitable(request()).wait())
```
Depending on what other modules I have installed (but not imported), this has vastly different behavior. In a reasonably clean virtual environment, it succeeds. In a slightly less clean one, I get:
```
Traceback (most recent call last):
  File "/Users/yury/scratch/code_a.py", line 14, in <module>
    print(spawn_for_awaitable(request()).wait())
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 224, in wait
    return self._exit_event.wait()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/event.py", line 124, in wait
    result = hub.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 310, in switch
    return self.greenlet.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 264, in main
    result = function(*args, **kwargs)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/asyncio.py", line 54, in _run
    return future.result()
  File "/Users/yury/scratch/code_a.py", line 11, in request
    response = await client.get('https://www.example.com/')
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1631, in send
    raise exc
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1625, in send
    await response.aread()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_models.py", line 914, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_models.py", line 914, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_models.py", line 932, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_models.py", line 998, in aiter_raw
    await self.aclose()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_models.py", line 1011, in aclose
    await self.stream.aclose()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 152, in aclose
    await self._stream.aclose()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_transports/default.py", line 254, in aclose
    await self._httpcore_stream.aclose()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 378, in aclose
    closing = self._pool._assign_requests_to_connections()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 248, in _assign_requests_to_connections
    elif connection.has_expired():
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 188, in has_expired
    return self._connection.has_expired()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/http11.py", line 277, in has_expired
    and self._network_stream.get_extra_info("is_readable")
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 92, in get_extra_info
    return is_socket_readable(sock)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_utils.py", line 32, in is_socket_readable
    rready, _, _ = select.select([sock_fd], [], [], 0)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/green/select.py", line 39, in select
    assert hub.greenlet is not current, 'do not call blocking functions from the mainloop'
AssertionError: do not call blocking functions from the mainloop
```

Code B:
```
import eventlet
import eventlet.hubs
eventlet.hubs.use_hub("eventlet.hubs.asyncio")

eventlet.monkey_patch()

from eventlet.hubs import hub
from eventlet.patcher import original
import concurrent
concurrent.futures.thread.threading = original("threading")
concurrent.futures.thread.queue = original("queue")

from eventlet.asyncio import spawn_for_awaitable

import httpx

async def request():
    async with httpx.AsyncClient() as client:
        response = await client.get('https://www.example.com/')
        return response.text

print(spawn_for_awaitable(request()).wait())
```
This also has some issues. In a clean virtual environment, this fails with:
```
Traceback (most recent call last):
  File "/Users/yury/scratch/code_b.py", line 15, in <module>
    concurrent.futures.thread.threading = original("threading")
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/__init__.py", line 53, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module concurrent.futures has no attribute thread
```
In a slightly less clean one, or if I manually add `from concurrent.futures import ThreadPoolExecutor`, I get:
```
Traceback (most recent call last):
  File "/Users/yury/scratch/code_b.py", line 22, in <module>
    print(spawn_for_awaitable(request()).wait())
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 224, in wait
    return self._exit_event.wait()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/event.py", line 124, in wait
    result = hub.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 310, in switch
    return self.greenlet.switch()
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/greenthread.py", line 264, in main
    result = function(*args, **kwargs)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/eventlet/asyncio.py", line 54, in _run
    return future.result()
  File "/Users/yury/scratch/code_b.py", line 19, in request
    response = await client.get('https://www.example.com/')
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 216, in connect_tcp
    async with create_task_group() as tg:
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/Users/yury/.virtualenvs/scratch/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
    self._sock_connect(fut, sock, address)
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py", line 516, in _sock_connect
    handle = self._add_writer(
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py", line 295, in _add_writer
    self._selector.register(fd, selectors.EVENT_WRITE,
  File "/Users/yury/.pyenv/versions/3.10.13/lib/python3.10/selectors.py", line 525, in register
    kev = select.kevent(key.fd, select.KQ_FILTER_WRITE,
AttributeError: module 'select' has no attribute 'kevent'
```

If I tell the monkey patch to *not* patch select (`eventlet.monkey_patch(select=False)`), it works in a clean environment, but goes  back to complaining about blocking: `AssertionError: do not call blocking functions from the mainloop` in an unclean one.

I am not sure what it is about my environment that is causing these behavior changes. I am guessing eventlet is trying to import something an succeeding.

**Comment by itamarst** [comment]
Code A is not really something I'd expect to work, you do need to monkeypatch.

Code B is a user error; you did `import concurrent` instead of `import concurrent.futures.thread`. In any  case this will be handled by the PR once it's merged.

The kevent issue could plausibly be a problem, we don't have macOS CI looks like :grimacing: So I'm going to add a macOS CI runner and then revisit the PR.

**Comment by itamarst** [comment]
PR #934 fixes the kqueue issue.

**Comment by itamarst** [comment]
Once #930 and #934 are merged, I will retest the original example. Assuming it works, I suggest closing this issue, and then you can open new issues if/when you encounter more problems.

**Comment by itamarst** [comment]
The original example works now. You can test it with `pip install --upgrade git+https://github.com/eventlet/eventlet.git` or wait for the next release.

**Comment by 4383** [comment]
Will prepare a new release tomorrow.

**Comment by itamarst** [comment]
I'd suggest merging #938 first before a release.

**Comment by 4383** [comment]
Sure

**Comment by itamarst** [comment]
A new release is out with multiple asyncio bugs, @yury-ppl-ai would be great if you could try again and let us know how it goes.
