### ISSUE TITLE
keystone-manage db_sync: AttributeError: 'NoneType' object has no attribute 'getcurrent'

### ISSUE THREAD

**Issue by farshan-dev** [eventlet/eventlet#953]
`Exception ignored in: <function _removeHandlerRef at 0x7f01819b43a0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 846, in _removeHandlerRef
  File "/usr/lib/python3.10/logging/__init__.py", line 226, in _acquireLock
  File "/usr/lib/python3.10/threading.py", line 164, in acquire
  File "/usr/lib/python3/dist-packages/eventlet/green/thread.py", line 34, in get_ident
AttributeError: 'NoneType' object has no attribute 'getcurrent'`

**Comment by farshan-dev** [comment]
i fixed this problem and commit it in https://github.com/farshan-dev/eventlet/tree/master

**Comment by 4383** [comment]
Please can you confirm the version of Eventlet that you are using there?
