### ISSUE TITLE
`requests.exceptions.ConnectionError` while using requests library with eventlet 

### ISSUE THREAD

**Issue by alamgiruk7** [eventlet/eventlet#974]
### Environment
`$ uname -a`: 

> Linux alamgir 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

`$ python3 -V`: 

> Python 3.10.12

`$ pip freeze`: 

> dnspython==2.6.1
> eventlet==0.35.1
> Flask==2.3.3
> Flask-Cors==4.0.0
> Flask-SocketIO==5.3.6
> greenlet==3.0.3
> requests==2.32.3
> urllib3==1.26.16

### Steps to reproduce the error
```
from flask import Flask
import requests

app = Flask(__name__)

@app.route('/fetch-data')
def fetch_data():
    try:
        res = requests.get("https://www.google.com")
        return res.text
    except requests.exceptions.RequestException as e:
        return str(e)

if __name__ == '__main__':
    app.run(debug=True)
```

**Note:** This throws the ConnectionError if you run the server through gunicorn and use eventlet i.e `gunicorn -k eventlet -w 1  app:app`

#### Second approach:
```
import eventlet

eventlet.monkey_patch()

from flask import Flask
import requests

app = Flask(__name__)

@app.route('/fetch-data')
def fetch_data():
    try:
        res = requests.get("https://www.google.com")
        return res.text
    except requests.exceptions.RequestException as e:
        return str(e)

if __name__ == '__main__':
    app.run(debug=True)
```
**Note:** This throws the ConnectionError if you run the server through Werkzeug development server i.e `python3 app.py`

**Comment by 4383** [comment]
Thanks for this bug report.
Is this bug observed via to a new code based on flask and eventlet or via an already existing code upgraded?

**Comment by alamgiruk7** [comment]
> Thanks for this bug report. Is this bug observed via to a new code based on flask and eventlet or via an already existing code upgraded?

Well, this is isn't directly related to flask or gunicorn. I guess the monkey patching interfere with `requests' normal blocking behavior, leading to unexpected issues and conflicts. If I use simple requests library in conjunction with eventlet without Flask or Gunicorn, it still don't work. Let me recreate it with a simple piece of code and share it with you.

**test.py**
```
import eventlet
import requests

eventlet.monkey_patch()

res = requests.get("https://www.google.com")
print(res.text)
```
**Output:**
```
Traceback (most recent call last):
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 463, in resolve
    return _proxy.query(name, rdtype, raise_on_no_answer=raises,
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 419, in query
    return end()
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 398, in end
    raise result[1]
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 379, in step
    a = fun(*args, **kwargs)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/dns/resolver.py", line 1364, in query
    return self.resolve(
  File "/path/to/python/dir/env/lib/python3.10/site-packages/dns/resolver.py", line 1321, in resolve
    timeout = self._compute_timeout(start, lifetime, resolution.errors)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/dns/resolver.py", line 1075, in _compute_timeout
    raise LifetimeTimeout(timeout=duration, errors=errors)
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.106 seconds: Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:127.0.0.53@53 answered udp() got an unexpected keyword argument 'ignore_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 558, in getaddrinfo
    qname, addrs = _getaddrinfo_lookup(host, family, flags)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 529, in _getaddrinfo_lookup
    raise err
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 518, in _getaddrinfo_lookup
    answer = resolve(host, qfamily, False, use_network=use_network)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 471, in resolve
    _raise_new_error(EAI_EAGAIN_ERROR)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/eventlet/support/greendns.py", line 100, in _raise_new_error
    raise error_instance.__class__(*error_instance.args)
socket.gaierror: [Errno -3] Lookup timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7c4ed003df30>: Failed to establish a new connection: [Errno -3] Lookup timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/path/to/python/dir/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7c4ed003df30>: Failed to establish a new connection: [Errno -3] Lookup timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/python/dir/test.py", line 6, in <module>
    res = requests.get("https://www.google.com")
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/python/dir/env/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7c4ed003df30>: Failed to establish a new connection: [Errno -3] Lookup timed out'))
```

**Comment by 4383** [comment]
You must monkey patch your env before importing `requests`.
On my laptop I just swapped both lines and by doing that your code now works as expected.

But, again, let me ask you if you are creating a new code/project, or using an existing one?
Eventlet is now deprecated and will be retired in a near future, so if you start a new project, I'd encourage you to use aiohttp rather than eventlet with requests or flask...

https://eventlet.readthedocs.io/en/latest/#warning

**Comment by 4383** [comment]
And if you are using an existing project, I'd encourage moving away from Eventlet, again by considering the usage of aiohttp (in accordance with your use case).

**Comment by 4383** [comment]
@alamgiruk7 Have you tried my previous proposal?
Can we close this issue?

**Comment by alamgiruk7** [comment]
Hey @4383, thanks for taking time to review. I tried your first suggestion i.e., monkey patching at the top of the file before importing anything but that didn't work. However, I switched to gevent and it worked fine. I believe we can close this issue.

**Comment by 4383** [comment]
Ok cool, thanks for your feedback
