### ISSUE TITLE
return in finally can swallow exceptions

### ISSUE THREAD

**Issue by iritkatriel** [eventlet/eventlet#986]
In https://github.com/eventlet/eventlet/blob/8637820f468268ffb0b8504561ea4772de23fcdb/eventlet/greenpool.py#L95
there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if a `BaseException` (such as `KeyboardInterrupt`) is raised from the `try` body, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by iritkatriel** [comment]
I'd imagine the adjustment is to change the finally body to:

```
            if coro is not None:
                coro = eventlet.getcurrent()
                self._spawn_done(coro)
```

**Comment by 4383** [comment]
Indeed, I confirm your observation.
I created a tiny reproducer:

```python
import time

def main():
    try:
        try:
            while True:
                print("boom")
                time.sleep(1)
        except (KeyboardInterrupt, SystemExit):
            raise
    finally:
        print("finally")
        #return

if __name__ == "__main__":
    main()
```

If I uncomment the `return` statement I obtain:
```
python3.12 test.py
boom
boom
^Cfinally
```

And without this return statement (statement commented):
```
python3.12 test.py
boom
boom
^Cfinally
Traceback (most recent call last):
  File "/tmp/test.py", line 16, in <module>
    main()
  File "/tmp/test.py", line 8, in main
    time.sleep(5)
KeyboardInterrupt
```

I don't know if this behaviour was voluntarily added if it is just something unexpected (a kind of bad logic).
Would you like to propose a fix?

**Comment by 4383** [comment]
I mean, would you like to submit a pull request to fix it?

**Comment by 4383** [comment]
On the other side, the WSGI module seems to have problems (apparently it fails) if `_spawn_n_impl` catch timeout:

https://github.com/eventlet/eventlet/blob/8637820f468268ffb0b8504561ea4772de23fcdb/tests/isolated/wsgi_connection_timeout.py#L11

But timeouts would be caught by the empty except statement and this part of the code do not reraise exceptions so...

https://github.com/eventlet/eventlet/blob/8637820f468268ffb0b8504561ea4772de23fcdb/eventlet/greenpool.py#L90

**Comment by iritkatriel** [comment]
> I mean, would you like to submit a pull request to fix it?

Don't wait for me, go ahead.

**Comment by 4383** [comment]
Well, if nobody else, apart you, complains about this behaviour, accounting that this behaviour is historical, and accounting the fact that we are close to abandon the maintenance of Eventlet, I won't submit a patch. I do not want to introduce a last minute side effect during that that everybody is trying to migrate away from Eventlet.

**Comment by 4383** [comment]
That's the kind of change that can blow up all the CI jobs of projects relying on Eventlet.

**Comment by 4383** [comment]
In all the case thanks you for your time and thanks for opening this github issue.
