### ISSUE TITLE
asyncio hub doesn't support multiple OS threads

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#994]
There are no tests for this or we would've noticed by now, but it seems `eventlet` expects different OS threads to be able to run greenlets. There are e.g. tests in `oslo.log` that rely on this.

Unfortunately the `asyncio` hub breaks when this is done, and seems to implicitly assume just one thread.

E.g. this runs on epolls hub:

```python
import time

import eventlet
import eventlet.patcher
eventlet.monkey_patch()

threading_orig = eventlet.patcher.original("threading")

def os_thread_2():
    print("THREAD 2 STARTED", time.time())
    eventlet.sleep(1)
    print("THREAD 2", time.time())
    eventlet.sleep(1)
    print("THREAD 2", time.time())

threading_orig.Thread(target=os_thread_2).start()
print("THREAD 1", time.time())
eventlet.sleep(0.99)
print("THREAD 1", time.time())
eventlet.sleep(3)
```

But when run with asyncio hub:

```
Exception in thread Thread-1 (os_thread_2):
Traceback (most recent call last):
  File "/home/itamarst/devel/eventlet/eventlet/hubs/__init__.py", line 104, in get_hub
    hub = _threadlocal.hub
          ^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'hub'. Did you mean: 'Hub'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/itamarst/devel/eventlet/eventlet/hubs/__init__.py", line 104, in get_hub
    hub = _threadlocal.hub
          ^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'hub'. Did you mean: 'Hub'?

...

Exception ignored in: <function BaseEventLoop.__del__ at 0x7197b4a77880>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_events.py", line 695, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 91, in close
    self._close_self_pipe()
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 98, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
                        ^^^^^^^^^^^
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
```

and other garbage.

**Comment by itamarst** [comment]
Testing with newer eventlet than above, I'm getting a different error, but it's still broken.
